// Seed challenge bank. Silly on-camera dares for ages 5-10, in Romanian.
// Each item is { text, seconds }. seconds > 0 shows a countdown ring on the
// card; seconds === 0 means no timer (open-ended or one-shot challenge).
window.CHALLENGES = [
  { text: "Dansează cel mai caraghios dans al tău!", seconds: 15 },
  { text: "Fă o mișcare de breakdance și îngheață ca o statuie!", seconds: 8 },
  { text: "Fredonează un cântec cunoscut!", seconds: 15 },
  { text: "Fă beatbox, cât de tare poți!", seconds: 15 },
  { text: "Fluieră o melodie cunoscută!", seconds: 15 },
  { text: "Poartă-te ca un robot stricat!", seconds: 15 },
  { text: "Imită sunetul și mersul unei maimuțe!", seconds: 15 },
  { text: "Desenează un câine cât mai repede!", seconds: 15 },
  { text: "Desenează o față caraghioasă!", seconds: 15 },
  { text: "Fă cea mai ciudată mutră și ține-o!", seconds: 8 },
  { text: "Stai într-un picior ca un flamingo!", seconds: 10 },
  { text: "Miorlăie ca o pisică furioasă!", seconds: 10 },
  { text: "Latră ca un cățeluș vesel!", seconds: 10 },
  { text: "Cântă la chitară invizibilă ca o vedetă rock!", seconds: 15 },
  { text: "Râzi cel mai ciudat râs al tău!", seconds: 10 },
  { text: "Mergi ca o rață prin cameră!", seconds: 15 },
  { text: "Mergi ca un crab, cu spatele!", seconds: 15 },
  { text: "Fă cel mai lent moonwalk posibil!", seconds: 10 },
  { text: "Comentează ca la meci tot ce faci acum!", seconds: 15 },
  { text: "Vorbește ca un extraterestru!", seconds: 15 },
  { text: "Sări ca un cangur prin cameră!", seconds: 15 },
  { text: "Fă cea mai lentă mișcare de karate!", seconds: 10 },
  { text: "Cântă alfabetul ca și cum ai fi supărat!", seconds: 15 },
  { text: "Fă pe prezentatorul de știri!", seconds: 15 },
  { text: "Imită un profesor supărat!", seconds: 15 },
  { text: "Fă sunete de mașină de curse!", seconds: 10 },
  { text: "Mimează că înoți, dar pe uscat!", seconds: 15 },
  { text: "Fă o reclamă caraghioasă la o banană!", seconds: 15 },
  { text: "Vorbește foarte, foarte încet, ca la încetinitor!", seconds: 10 },
  { text: "Fă cea mai tare voce de monstru!", seconds: 10 },
  { text: "Ține o poziție de yoga caraghioasă!", seconds: 10 },
  { text: "Fă cea mai dramatică poză de supererou!", seconds: 8 },
  { text: "Numără până la 10 în cea mai ciudată voce!", seconds: 10 },
  { text: "Fă pe robotul care se defectează la final!", seconds: 15 },
  { text: "Fă pe pisica ce se spală!", seconds: 10 },
  { text: "Spune cât mai repede: capra calcă piatra, piatra crapă-n patru!", seconds: 10 },
  { text: "Spune o glumă cât mai amuzantă!", seconds: 0 },
  { text: "Fă cea mai bună imitație de animal de la zoo!", seconds: 0 },
  { text: "Desenează un monstru prietenos!", seconds: 0 },
  { text: "Inventează un salut secret cu mâinile!", seconds: 0 },
  { text: "Spune numele tău invers, literă cu literă!", seconds: 0 },
  { text: "Fă cea mai bună imitație a unui profesor!", seconds: 0 },
  { text: "Inventează un nume nou și amuzant pentru tine!", seconds: 0 },
  { text: "Arată cum mergi când ești foarte, foarte obosit!", seconds: 0 },
  { text: "Arată cum mergi când ești foarte grăbit la baie!", seconds: 0 },
  { text: "Spune alfabetul cântând!", seconds: 0 },
  { text: "Fă cea mai teatrală plecăciune de final de spectacol!", seconds: 0 },
  { text: "Inventează un nume caraghios pentru un animal de companie imaginar!", seconds: 0 },
  { text: "Spune ce ai mânca dacă ai fi un dinozaur, ca un dinozaur!", seconds: 0 },
  { text: "Fă-ți autograful în aer, ca și cum ai fi celebru!", seconds: 0 },
  { text: "Arată cel mai mândru mers de pe covorul roșu!", seconds: 0 },
  { text: "Fă cea mai serioasă mutră posibilă, fără să râzi!", seconds: 0 },
  { text: "Inventează o poreclă amuzantă pentru cel mai bun prieten!", seconds: 0 },
  { text: "Arată ce faci dimineața, dar cu mișcări încetinite!", seconds: 0 },
  { text: "Fă cea mai exagerată reacție la un cadou grozav!", seconds: 0 },
  { text: "Spune o poezie scurtă, inventată pe loc!", seconds: 0 },
  { text: "Arată cum ai merge dacă ai avea pantofi de clovn!", seconds: 0 },
  { text: "Fă cea mai bună imitație a unui prezentator de vreme!", seconds: 0 },
  { text: "Inventează un dans nou și dă-i un nume!", seconds: 0 },
  { text: "Arată cea mai mare bucurie posibilă, fără cuvinte!", seconds: 0 },
];
