// Seed game bank: traditional Romanian children's games for ages 6-10.
// Each item is { id, name, icon, players, description, steps: [{ icon, text }] }.
// `icon` keys reference <symbol id="icon-KEY"> defined in the sprite in index.html.
window.GAMES = [
  {
    id: "leapsa",
    name: "Leapșa",
    icon: "tag-touch",
    players: "3 sau mai mulți copii",
    description: "Cel mai simplu joc de fugărit: cine e „prins” trebuie să atingă pe altcineva ca să scape.",
    steps: [
      { icon: "point", text: "Un copil este ales să fie „prins” la început." },
      { icon: "run", text: "Toți ceilalți copii fug repede în toate părțile." },
      { icon: "tag-touch", text: "Cel „prins” aleargă și încearcă să atingă un alt copil." },
      { icon: "swap", text: "Cine e atins devine noul „prins” și jocul o ia de la capăt!" },
    ],
  },
  {
    id: "vatia",
    name: "De-a v-ați ascunselea",
    icon: "hide",
    players: "3 sau mai mulți copii",
    description: "Un copil numără cu ochii închiși, iar restul se ascund cât mai bine.",
    steps: [
      { icon: "count", text: "Un copil stă cu ochii închiși și numără până la 20, tare." },
      { icon: "hide", text: "Ceilalți copii se ascund repede cât timp el numără." },
      { icon: "seek", text: "După ce termină de numărat, pleacă să îi caute pe ceilalți." },
      { icon: "tag-touch", text: "Primul copil găsit devine cel care numără data viitoare!" },
    ],
  },
  {
    id: "sotron",
    name: "Șotron",
    icon: "grid",
    players: "1 sau mai mulți copii, pe rând",
    description: "Se sare într-un picior peste pătrățele desenate pe jos, numerotate.",
    steps: [
      { icon: "grid", text: "Desenați pe jos, cu creta, un șotron cu pătrățele numerotate." },
      { icon: "throw", text: "Aruncă o pietricică în pătratul cu numărul 1." },
      { icon: "hop", text: "Sari într-un picior peste pătrățele, fără să calci pe linii." },
      { icon: "turn", text: "La întoarcere, culege pietricica din drum și treci la numărul următor!" },
    ],
  },
  {
    id: "baba-oarba",
    name: "Baba oarbă",
    icon: "blindfold",
    players: "4 sau mai mulți copii",
    description: "Un copil e legat la ochi și trebuie să prindă și să ghicească pe cineva, pe pipăite.",
    steps: [
      { icon: "blindfold", text: "Un copil este legat la ochi cu o eșarfă." },
      { icon: "spin", text: "Este învârtit ușor de câteva ori, ca să se învârtă puțin capul." },
      { icon: "reach", text: "Ceilalți se mișcă în tăcere în jurul lui, iar el încearcă să prindă pe cineva." },
      { icon: "reach", text: "Dacă îl prinde și îi ghicește numele, copilul prins devine noua „babă oarbă”!" },
    ],
  },
  {
    id: "statuile",
    name: "Statuile",
    icon: "freeze",
    players: "3 sau mai mulți copii",
    description: "Toți aleargă spre cel care „conduce”, dar trebuie să înghețe ca o statuie când se întoarce.",
    steps: [
      { icon: "wall", text: "Un copil stă cu fața la perete și strigă „1, 2, 3, stop!”." },
      { icon: "run", text: "Cât timp el numără, ceilalți aleargă cu spor spre el." },
      { icon: "freeze", text: "Când spune „stop”, se întoarce repede — toți trebuie să înghețe pe loc!" },
      { icon: "out", text: "Cine se mișcă se întoarce la start. Primul care ajunge la perete câștigă!" },
    ],
  },
  {
    id: "ratele-vanatori",
    name: "Rățele și vânători",
    icon: "throw",
    players: "6 sau mai mulți copii",
    description: "„Vânătorii” formează un cerc și încearcă să atingă „rățele” cu o minge moale, pe jos.",
    steps: [
      { icon: "group-circle", text: "Jumătate dintre copii, „vânătorii”, formează un cerc mare." },
      { icon: "standing", text: "Ceilalți copii, „rățele”, stau în interiorul cercului." },
      { icon: "throw", text: "Vânătorii aruncă o minge moale, pe jos, ca să atingă rățele." },
      { icon: "dodge", text: "Rățele fug și se feresc; cine e atins iese, apoi schimbați rolurile!" },
    ],
  },
  {
    id: "scaune-muzicale",
    name: "Scaunele muzicale",
    icon: "chair",
    players: "4 sau mai mulți copii",
    description: "Se aranjează scaune în cerc, cu unul mai puțin decât numărul copiilor, și se dansează pe muzică.",
    steps: [
      { icon: "chair", text: "Așezați scaunele în cerc, cu un scaun mai puțin decât numărul copiilor." },
      { icon: "music", text: "Toată lumea dansează în jurul scaunelor cât timp cântă muzica." },
      { icon: "freeze", text: "Când muzica se oprește brusc, toți aleargă să se așeze pe un scaun!" },
      { icon: "out", text: "Cine rămâne în picioare iese din joc; se scoate un scaun și se continuă!" },
    ],
  },
  {
    id: "telefonul-fara-fir",
    name: "Telefonul fără fir",
    icon: "whisper",
    players: "4 sau mai mulți copii",
    description: "Copiii își șoptesc un mesaj din ureche în ureche, până la ultimul din șir.",
    steps: [
      { icon: "chain-line", text: "Copiii stau așezați într-un șir sau cerc." },
      { icon: "whisper", text: "Primul copil șoptește o propoziție scurtă la urechea următorului." },
      { icon: "ear", text: "Fiecare copil șoptește mai departe exact ce a auzit, fără să repete tare." },
      { icon: "laugh", text: "Ultimul copil spune tare ce a auzit — de obicei e cu totul altceva, și e amuzant!" },
    ],
  },
  {
    id: "stafeta",
    name: "Ștafeta",
    icon: "baton-pass",
    players: "4 sau mai mulți copii, în echipe",
    description: "Copiii se împart în echipe și aleargă pe rând, predând un obiect coechipierului următor.",
    steps: [
      { icon: "group-circle", text: "Împărțiți copiii în două sau mai multe echipe egale." },
      { icon: "chain-line", text: "Fiecare echipă stă la rând, în spatele liniei de start." },
      { icon: "run", text: "Primul copil aleargă până la un semn și se întoarce în fugă." },
      { icon: "baton-pass", text: "Predă ștafeta următorului coechipier — echipa care termină prima câștigă!" },
    ],
  },
  {
    id: "frigul-fierbinte",
    name: "Frigul și fierbinte",
    icon: "hidden-object",
    players: "2 sau mai mulți copii",
    description: "Un obiect e ascuns, iar ceilalți îl caută ghidați de „cald” sau „rece”, după cât de aproape sunt.",
    steps: [
      { icon: "hidden-object", text: "Un copil ascunde un obiect mic, cât timp ceilalți nu se uită." },
      { icon: "seek", text: "Ceilalți copii încep să caute obiectul prin cameră." },
      { icon: "hot", text: "Cel care a ascuns spune „fierbinte” când cineva se apropie de obiect." },
      { icon: "cold", text: "...și „rece” când se îndepărtează, până când cineva îl găsește!" },
    ],
  },
];
