// Seed prompt bank for Desenează (draw) mode. Silly things to sketch for kids
// ages 5-10, in Romanian. Each item is { text, seconds } — same shape as
// challenges.js. Unlike challenges, every entry has seconds > 0: the draw
// mode always runs a countdown that locks the canvas at 0 (the kid can also
// finish early via the Termină! button — see draw.js).
window.DRAW_PROMPTS = [
  { text: "Desenează un monstru care mănâncă doar broccoli!", seconds: 30 },
  { text: "Desenează-ți animalul de companie visat, cât mai ciudat!", seconds: 30 },
  { text: "Desenează un extraterestru care tocmai a aterizat în curtea ta!", seconds: 30 },
  { text: "Desenează cel mai mare sandviș din lume!", seconds: 30 },
  { text: "Desenează-te pe tine ca super-erou!", seconds: 30 },
  { text: "Desenează un dinozaur care poartă pantofi de sport!", seconds: 30 },
  { text: "Desenează o pizza cu cele mai ciudate toppinguri!", seconds: 30 },
  { text: "Desenează un robot care își face temele!", seconds: 30 },
  { text: "Desenează un pește care a învățat să zboare!", seconds: 30 },
  { text: "Desenează cea mai haioasă pălărie din lume!", seconds: 30 },

  { text: "Desenează un monstru care se teme de întuneric și doarme cu veioza aprinsă!", seconds: 30 },
  { text: "Desenează un monstru cu 100 de ochi dar care nu vede nimic!", seconds: 30 },
  { text: "Desenează un monstru care colecționează șosete pierdute!", seconds: 30 },
  { text: "Desenează un monstru care plânge când aude muzică tristă!", seconds: 30 },
  { text: "Desenează un monstru cu părul făcut din spaghete!", seconds: 30 },
  { text: "Desenează un monstru care se ascunde sub pat dar are picioare prea mari!", seconds: 30 },
  { text: "Desenează un monstru care face baloane de săpun din nas!", seconds: 30 },
  { text: "Desenează un monstru cu dinți de vată de zahăr!", seconds: 30 },
  { text: "Desenează un monstru care se sperie de propria umbră!", seconds: 30 },
  { text: "Desenează un monstru cu 3 brațe, fiecare ținând o înghețată!", seconds: 30 },
  { text: "Desenează un monstru care mănâncă doar sarmale!", seconds: 30 },
  { text: "Desenează un monstru care strănută confetti!", seconds: 30 },
  { text: "Desenează un monstru cu urechi de elefant și coadă de pisică!", seconds: 30 },
  { text: "Desenează un monstru care poartă papuci de iepuraș!", seconds: 30 },
  { text: "Desenează un monstru care trăiește într-un dulap plin cu jucării!", seconds: 30 },
  { text: "Desenează un monstru care cântă la chitară cu 3 coarde rupte!", seconds: 30 },
  { text: "Desenează un monstru cu o singură sprânceană uriașă!", seconds: 30 },
  { text: "Desenează un monstru care colecționează nasturi colorați!", seconds: 30 },
  { text: "Desenează un monstru care se piaptănă cu o furculiță!", seconds: 30 },
  { text: "Desenează un monstru care doarme atârnat cu capul în jos, ca un liliac!", seconds: 30 },

  { text: "Desenează o pisică ce conduce un tractor!", seconds: 30 },
  { text: "Desenează un câine care poartă ochelari de soare și surfează!", seconds: 30 },
  { text: "Desenează o girafă cu gâtul înnodat!", seconds: 30 },
  { text: "Desenează un elefant care face baloane din trompă!", seconds: 30 },
  { text: "Desenează o broască țestoasă cu rachete la carapace!", seconds: 30 },
  { text: "Desenează un urs care coace prăjituri!", seconds: 30 },
  { text: "Desenează o veveriță cu o coadă de trei ori mai mare decât ea!", seconds: 30 },
  { text: "Desenează un iepure care joacă fotbal cu un morcov!", seconds: 30 },
  { text: "Desenează o zebră cu dungi în carouri!", seconds: 30 },
  { text: "Desenează un leu cu coama făcută din baloane!", seconds: 30 },
  { text: "Desenează o vacă ce zboară cu o umbrelă!", seconds: 30 },
  { text: "Desenează un porc care cântă la pian!", seconds: 30 },
  { text: "Desenează un cangur cu buzunarul plin de înghețată!", seconds: 30 },
  { text: "Desenează o cămilă cu 5 cocoașe!", seconds: 30 },
  { text: "Desenează un papagal care vorbește doar în rime!", seconds: 30 },
  { text: "Desenează o maimuță care se dă cu skateboard-ul!", seconds: 30 },
  { text: "Desenează un rechin cu papion și servietă!", seconds: 30 },
  { text: "Desenează o pinguină care poartă șapcă de baseball!", seconds: 30 },
  { text: "Desenează un liliac care se teme de întuneric!", seconds: 30 },
  { text: "Desenează o albină cu o pălărie de petrecere!", seconds: 30 },

  { text: "Desenează un extraterestru care colecționează pietricele de pe Pământ!", seconds: 30 },
  { text: "Desenează o farfurie zburătoare făcută din brânză!", seconds: 30 },
  { text: "Desenează un astronaut care a uitat casca acasă!", seconds: 30 },
  { text: "Desenează o planetă cu inele din acadele!", seconds: 30 },
  { text: "Desenează un extraterestru cu 2 capete care sunt cei mai buni prieteni!", seconds: 30 },
  { text: "Desenează o rachetă construită din cutii de carton!", seconds: 30 },
  { text: "Desenează un extraterestru verde care adoră mămăliga!", seconds: 30 },
  { text: "Desenează o stea căzătoare care s-a rătăcit pe Pământ!", seconds: 30 },
  { text: "Desenează o lună cu față zâmbitoare și coșuri!", seconds: 30 },
  { text: "Desenează un extraterestru care încearcă să învețe să meargă pe role!", seconds: 30 },
  { text: "Desenează un robot spațial care culege flori!", seconds: 30 },
  { text: "Desenează o cometă cu coadă de curcubeu!", seconds: 30 },
  { text: "Desenează un extraterestru speriat de un fluture!", seconds: 30 },
  { text: "Desenează o navă spațială pilotată de un pisoi!", seconds: 30 },

  { text: "Desenează un robot care adoră să danseze breakdance!", seconds: 30 },
  { text: "Desenează un robot de bucătărie care arde tot ce gătește!", seconds: 30 },
  { text: "Desenează un robot cu antene care prind doar posturi de desene animate!", seconds: 30 },
  { text: "Desenează un robot care plânge cu ulei în loc de lacrimi!", seconds: 30 },
  { text: "Desenează un robot uriaș construit din piese de Lego!", seconds: 30 },
  { text: "Desenează un robot de companie pentru un pește auriu!", seconds: 30 },
  { text: "Desenează un robot care se sperie de furtuni!", seconds: 30 },
  { text: "Desenează un robot cu roți de bicicletă în loc de picioare!", seconds: 30 },
  { text: "Desenează un robot grădinar care udă florile cu suc!", seconds: 30 },
  { text: "Desenează un robot minuscul care trăiește într-un ceas!", seconds: 30 },
  { text: "Desenează un robot care colecționează șuruburi ruginite!", seconds: 30 },
  { text: "Desenează un robot ce se crede câine și latră!", seconds: 30 },
  { text: "Desenează un robot care face bule de săpun în loc de fum!", seconds: 30 },
  { text: "Desenează un robot care se îmbracă în costum de dinozaur!", seconds: 30 },

  { text: "Desenează un dinozaur care își perie dinții cu o mătură!", seconds: 30 },
  { text: "Desenează un dinozaur minuscul, cât o pisică!", seconds: 30 },
  { text: "Desenează un dinozaur care poartă rucsac de școală!", seconds: 30 },
  { text: "Desenează un dinozaur cu pene colorate ca un curcubeu!", seconds: 30 },
  { text: "Desenează un dinozaur care se joacă baschet cu o minge uriașă!", seconds: 30 },
  { text: "Desenează un dinozaur speriat de un șoricel!", seconds: 30 },
  { text: "Desenează un dinozaur care cântă la tobe cu coada!", seconds: 30 },
  { text: "Desenează un dinozaur cu ochelari de citit!", seconds: 30 },
  { text: "Desenează un dinozaur care înoată cu colac de cauciuc!", seconds: 30 },
  { text: "Desenează un dinozaur care poartă o eșarfă foarte, foarte lungă!", seconds: 30 },

  { text: "Desenează o pizza cu picioare care fuge de tine!", seconds: 30 },
  { text: "Desenează un hamburger cât o casă!", seconds: 30 },
  { text: "Desenează o înghețată care se plimbă cu bicicleta!", seconds: 30 },
  { text: "Desenează un covrig cu ochi și zâmbet!", seconds: 30 },
  { text: "Desenează un tort care explodează cu confetti!", seconds: 30 },
  { text: "Desenează o banană deghizată în super-erou!", seconds: 30 },
  { text: "Desenează un morcov care poartă coroană de rege!", seconds: 30 },
  { text: "Desenează o gogoașă cu 100 de sprinkles!", seconds: 30 },
  { text: "Desenează un castravete care cântă la microfon!", seconds: 30 },
  { text: "Desenează o prăjitură cu picioare de păianjen!", seconds: 30 },
  { text: "Desenează un ou prăjit care poartă pălărie de bucătar!", seconds: 30 },
  { text: "Desenează o ciupercă gigantă cu ferestre și ușă, ca o căsuță!", seconds: 30 },
  { text: "Desenează un ardei gras care face karate!", seconds: 30 },
  { text: "Desenează o vată de zahăr în formă de nor furios!", seconds: 30 },
  { text: "Desenează un măr cu un vierme prieten, nu dușman!", seconds: 30 },
  { text: "Desenează o clătită care zboară ca un frisbee!", seconds: 30 },

  { text: "Desenează o mașină cu roți de brânză!", seconds: 30 },
  { text: "Desenează un tren care merge pe nori!", seconds: 30 },
  { text: "Desenează o barcă construită din pantofi vechi!", seconds: 30 },
  { text: "Desenează un avion cu aripi de fluture!", seconds: 30 },
  { text: "Desenează un submarin în formă de pește uriaș!", seconds: 30 },
  { text: "Desenează o bicicletă cu trei roți în față și una în spate!", seconds: 30 },
  { text: "Desenează un tractor condus de o găină!", seconds: 30 },
  { text: "Desenează o mașină de pompieri roz, cu sirenă care cântă!", seconds: 30 },
  { text: "Desenează un balon cu aer cald în formă de dovleac!", seconds: 30 },
  { text: "Desenează o trotinetă cu motor de rachetă!", seconds: 30 },
  { text: "Desenează un autobuz școlar plin cu maimuțe!", seconds: 30 },
  { text: "Desenează un elicopter cu elice făcute din creioane colorate!", seconds: 30 },
  { text: "Desenează o săniuță trasă de pinguini!", seconds: 30 },
  { text: "Desenează un camion de gunoi care miroase a flori!", seconds: 30 },

  { text: "Desenează un super-erou a cărui superputere e să facă cea mai tare gogoașă!", seconds: 30 },
  { text: "Desenează o super-eroină care zboară cu ajutorul unei umbrele!", seconds: 30 },
  { text: "Desenează un pirat care se teme de apă!", seconds: 30 },
  { text: "Desenează un cavaler cu armură făcută din carton!", seconds: 30 },
  { text: "Desenează o prințesă care preferă noroiul în loc de rochii!", seconds: 30 },
  { text: "Desenează un vrăjitor care își pierde mereu bagheta!", seconds: 30 },
  { text: "Desenează un ninja care se împiedică de propriile picioare!", seconds: 30 },
  { text: "Desenează un cowboy care călărește o gâscă!", seconds: 30 },
  { text: "Desenează un detectiv cu lupă și mustață falsă!", seconds: 30 },
  { text: "Desenează un super-erou al cărui costum e din pijamale!", seconds: 30 },
  { text: "Desenează un spion care se ascunde într-un ghiveci de flori!", seconds: 30 },
  { text: "Desenează un rege care domnește peste un regat de jucării!", seconds: 30 },
  { text: "Desenează un explorator pierdut într-o pădure de bomboane!", seconds: 30 },
  { text: "Desenează un magician a cărui pălărie e plină cu iepurași ce nu vor să iasă!", seconds: 30 },

  { text: "Desenează un dragon care se teme de foc!", seconds: 30 },
  { text: "Desenează un unicorn cu coama făcută din vată de zahăr!", seconds: 30 },
  { text: "Desenează o zână care a pierdut una dintre aripi!", seconds: 30 },
  { text: "Desenează un elf care colecționează pantofi ciudați!", seconds: 30 },
  { text: "Desenează un troll simpatic care adoră florile!", seconds: 30 },
  { text: "Desenează o sirenă cu coadă în carouri!", seconds: 30 },
  { text: "Desenează un pitic care trăiește într-o ciupercă uriașă!", seconds: 30 },
  { text: "Desenează un centaur care participă la o cursă de biciclete!", seconds: 30 },
  { text: "Desenează o fantomă care se sperie de întuneric!", seconds: 30 },
  { text: "Desenează un yeti care se topește la soare!", seconds: 30 },
  { text: "Desenează un vampir vegetarian care adoră usturoiul!", seconds: 30 },
  { text: "Desenează un balaur cu două capete, unul vesel și unul somnoros!", seconds: 30 },
  { text: "Desenează un spiriduș care șterpelește șosete!", seconds: 30 },
  { text: "Desenează o hidră cu 3 capete, toate purtând aceeași pălărie caraghioasă!", seconds: 30 },
  { text: "Desenează un grifon cu aripi de fluture!", seconds: 30 },
  { text: "Desenează un gnom de grădină care prinde viață noaptea!", seconds: 30 },

  { text: "Desenează un ceas cu picioare care fuge de tine!", seconds: 30 },
  { text: "Desenează o umbrelă care zboară ca un elicopter!", seconds: 30 },
  { text: "Desenează un aspirator care mănâncă tot ce vede!", seconds: 30 },
  { text: "Desenează o pernă cu față și zâmbet mare!", seconds: 30 },
  { text: "Desenează un scaun cu roți care face curse!", seconds: 30 },
  { text: "Desenează o oglindă caraghioasă care te face să arăți ca o broască!", seconds: 30 },
  { text: "Desenează un termos care scoate aburi în formă de inimioare!", seconds: 30 },
  { text: "Desenează o carte care sare din raft și zboară prin cameră!", seconds: 30 },
  { text: "Desenează un telefon vechi cu picioare de păianjen!", seconds: 30 },
  { text: "Desenează o lampă care visează să fie stea!", seconds: 30 },
  { text: "Desenează un fierăstrău care taie doar plăcinte!", seconds: 30 },
  { text: "Desenează o periuță de dinți care se plictisește de dinți!", seconds: 30 },
  { text: "Desenează un ghiozdan care mănâncă mereu temele!", seconds: 30 },
  { text: "Desenează o pereche de șosete care nu vor să stea împreună!", seconds: 30 },

  { text: "Desenează un nor care plânge lapte în loc de ploaie!", seconds: 30 },
  { text: "Desenează un curcubeu care se rostogolește ca o roată!", seconds: 30 },
  { text: "Desenează un soare cu ochelari de soare!", seconds: 30 },
  { text: "Desenează un fulg de nea uriaș, cât o mașină!", seconds: 30 },
  { text: "Desenează un vulcan care erupe înghețată!", seconds: 30 },
  { text: "Desenează un copac cu fructe care vorbesc!", seconds: 30 },
  { text: "Desenează o floare care cântă când bate vântul!", seconds: 30 },

  { text: "Desenează o pereche de pantofi care aleargă singuri!", seconds: 30 },
  { text: "Desenează o pălărie atât de înaltă încât ajunge la nori!", seconds: 30 },
  { text: "Desenează o eșarfă atât de lungă încât se înfășoară de 10 ori în jurul gâtului!", seconds: 30 },
  { text: "Desenează niște ochelari cu ștergătoare de parbriz!", seconds: 30 },
  { text: "Desenează o mănușă cu degete de mărimi diferite!", seconds: 30 },
  { text: "Desenează o cravată vie care se mișcă singură!", seconds: 30 },
  { text: "Desenează o rochie făcută din frunze de toamnă!", seconds: 30 },
  { text: "Desenează niște ghete de cauciuc pentru sărit în bălți uriașe!", seconds: 30 },
  { text: "Desenează o coroană din creioane colorate!", seconds: 30 },
  { text: "Desenează un rucsac cu propriul lui creier!", seconds: 30 },

  { text: "Desenează un monstru care râgâie curcubeu!", seconds: 30 },
  { text: "Desenează un balon care se dezumflă făcând cel mai amuzant sunet!", seconds: 30 },
  { text: "Desenează pe cineva care strănută atât de tare încât zboară pe spate!", seconds: 30 },
  { text: "Desenează un extraterestru care comunică doar prin sughițuri!", seconds: 30 },
  { text: "Desenează un dragon care scoate pe nas fum cu miros de brânză!", seconds: 30 },
  { text: "Desenează un robot care trage vânturi cu aburi colorați!", seconds: 30 },
  { text: "Desenează cea mai mare bășică de muci din lume!", seconds: 30 },
  { text: "Desenează un monstru care se scobește în nas și găsește o comoară!", seconds: 30 },
  { text: "Desenează un elefant care strănută atât de tare încât suflă pălăriile tuturor!", seconds: 30 },
  { text: "Desenează un personaj care râgâie literele alfabetului!", seconds: 30 },
  { text: "Desenează un porc care se rostogolește vesel prin noroi!", seconds: 30 },
  { text: "Desenează un câine care doarme sforăind ca un tractor!", seconds: 30 },
  { text: "Desenează un monstru care își suflă nasul într-o pânză de păianjen!", seconds: 30 },
  { text: "Desenează cel mai puturos pantof din lume, cu un nor verde deasupra!", seconds: 30 },

  { text: "Desenează-te pe tine peste 100 de ani!", seconds: 30 },
  { text: "Desenează un frate sau o soră transformați în super-erou obosit!", seconds: 30 },
  { text: "Desenează-ți bunica zburând cu mătura, ca o vrăjitoare simpatică!", seconds: 30 },
  { text: "Desenează-te pe tine gigant, mai mare decât blocul!", seconds: 30 },
  { text: "Desenează-ți mama sau tatăl ca un supererou al gospodăriei!", seconds: 30 },
  { text: "Desenează-te pe tine ca rege sau regină al camerei tale!", seconds: 30 },
  { text: "Desenează-ți cel mai bun prieten ca personaj de desene animate!", seconds: 30 },

  { text: "Desenează o stea de mare care poartă ochelari de soare!", seconds: 30 },
  { text: "Desenează un pește clovn cu pălărie de petrecere!", seconds: 30 },
  { text: "Desenează o meduză care plutește ca un balon!", seconds: 30 },
  { text: "Desenează un crab care merge cu role!", seconds: 30 },
  { text: "Desenează un delfin care sare printr-un cerc de săpun!", seconds: 30 },
  { text: "Desenează o caracatiță care cântă la opt tobe deodată!", seconds: 30 },
  { text: "Desenează un pește-spadă care se bărbierește!", seconds: 30 },
  { text: "Desenează un homar roșu care poartă papion!", seconds: 30 },
  { text: "Desenează un cal de mare cât o balenă!", seconds: 30 },
  { text: "Desenează o scoică ce zâmbește larg!", seconds: 30 },

  { text: "Desenează un fluture cu aripi în carouri!", seconds: 30 },
  { text: "Desenează o gărgăriță cu 20 de puncte colorate!", seconds: 30 },
  { text: "Desenează o omidă care poartă o sută de pantofi!", seconds: 30 },
  { text: "Desenează un greiere care cântă la vioară!", seconds: 30 },
  { text: "Desenează o furnică ce cară un sandviș uriaș!", seconds: 30 },
  { text: "Desenează o libelulă cu aripi de curcubeu!", seconds: 30 },
  { text: "Desenează un păianjen care tricotează o pânză roz!", seconds: 30 },
  { text: "Desenează o albină obosită care doarme într-o floare!", seconds: 30 },

  { text: "Desenează o minge de fotbal cu față speriată!", seconds: 30 },
  { text: "Desenează o rachetă de tenis care joacă singură!", seconds: 30 },
  { text: "Desenează o bicicletă cu roți pătrate!", seconds: 30 },
  { text: "Desenează un skateboard care zboară!", seconds: 30 },
  { text: "Desenează o minge de baschet care sare până la lună!", seconds: 30 },
  { text: "Desenează o coardă de sărit ce se mișcă singură!", seconds: 30 },
  { text: "Desenează o trambulină uriașă în formă de pizza!", seconds: 30 },
  { text: "Desenează niște patine cu rotile care aleargă fără picioare!", seconds: 30 },

  { text: "Desenează o umbrelă care urăște ploaia!", seconds: 30 },
  { text: "Desenează o lingură și o furculiță care dansează împreună!", seconds: 30 },
  { text: "Desenează un pahar care râde cu suc pe gură!", seconds: 30 },
  { text: "Desenează o pernă care sforăie tare!", seconds: 30 },
  { text: "Desenează un ceainic care fluieră o melodie!", seconds: 30 },
  { text: "Desenează o oglindă care se piaptănă singură!", seconds: 30 },
  { text: "Desenează un covor care zboară doar puțin, aproape de podea!", seconds: 30 },
  { text: "Desenează un ceas deșteptător furios dimineața!", seconds: 30 },
  { text: "Desenează o cutie de creioane care se ceartă cine e cel mai colorat!", seconds: 30 },
  { text: "Desenează un termometru care tremură de frig!", seconds: 30 },

  { text: "Desenează un spiriduș de zăpadă cu nas de morcov!", seconds: 30 },
  { text: "Desenează un pui de dragon care strănută scântei!", seconds: 30 },
  { text: "Desenează o zână a dulciurilor cu aripi de acadea!", seconds: 30 },
  { text: "Desenează un gnom pitic care poartă o pălărie cât el de mare!", seconds: 30 },
  { text: "Desenează un pui de unicorn care încă învață să zboare!", seconds: 30 },
  { text: "Desenează un spiriduș verde ce trăiește într-o ghindă!", seconds: 30 },
  { text: "Desenează o broscuță fermecată cu coroană strâmbă!", seconds: 30 },
  { text: "Desenează un ursuleț de pluș care prinde viață noaptea!", seconds: 30 },

  { text: "Desenează un nor cu ochelari și mustață!", seconds: 30 },
  { text: "Desenează un fulger care face cu ochiul!", seconds: 30 },
  { text: "Desenează o stea care cântă la chitară!", seconds: 30 },
  { text: "Desenează un vânt vesel care suflă pălăriile tuturor!", seconds: 30 },
  { text: "Desenează o ploaie de bomboane colorate!", seconds: 30 },
  { text: "Desenează o lună care poartă căciulă de iarnă!", seconds: 30 },

  { text: "Desenează o înghețată care se topește de râs!", seconds: 30 },
  { text: "Desenează un ardei iute cu față furioasă!", seconds: 30 },
  { text: "Desenează o lămâie acră care face o grimasă!", seconds: 30 },
  { text: "Desenează un fursec cu ochi mari și gură zâmbitoare!", seconds: 30 },
  { text: "Desenează o portocală care joacă baschet!", seconds: 30 },
  { text: "Desenează un pahar de limonadă cu paie strâmbă!", seconds: 30 },

  { text: "Desenează o bufniță care poartă ochelari de citit!", seconds: 30 },
  { text: "Desenează un arici cu baloane în loc de țepi!", seconds: 30 },
  { text: "Desenează o rață cu cizme de ploaie galbene!", seconds: 30 },
  { text: "Desenează un cal care sare peste un curcubeu!", seconds: 30 },
];
