// Seed prompt bank for Desenează (draw) mode. Silly things to sketch for
// kids ages 5-10. Each item is { text, seconds } — same shape as
// challenges.js. Unlike challenges, every entry has seconds > 0: the draw
// mode always runs a countdown that locks the canvas at 0 (the kid can also
// finish early via the Termină!/Finish! button — see draw.js). i18n.js
// picks _RO or _EN at load time based on the active language — keep both
// arrays the same length and order.
window.DRAW_PROMPTS_RO = [
  { text: "Desenează un monstru care mănâncă doar broccoli!", seconds: 30 },
  { text: "Desenează-ți animalul de companie visat, cât mai ciudat!", seconds: 30 },
  { text: "Desenează un extraterestru care tocmai a aterizat în curtea ta!", seconds: 30 },
  { text: "Desenează cel mai mare sandviș din lume!", seconds: 30 },
  { text: "Desenează-te pe tine ca super-erou!", seconds: 30 },
  { text: "Desenează un dinozaur care poartă pantofi de sport!", seconds: 30 },
  { text: "Desenează o pizza cu cele mai ciudate toppinguri!", seconds: 30 },
  { text: "Desenează un robot care își face temele!", seconds: 30 },
  { text: "Desenează un pește care a învățat să zboare!", seconds: 30 },
  { text: "Desenează cea mai haioasă pălărie din lume!", seconds: 30 },

  { text: "Desenează un monstru care se teme de întuneric și doarme cu veioza aprinsă!", seconds: 30 },
  { text: "Desenează un monstru cu 100 de ochi dar care nu vede nimic!", seconds: 30 },
  { text: "Desenează un monstru care colecționează șosete pierdute!", seconds: 30 },
  { text: "Desenează un monstru care plânge când aude muzică tristă!", seconds: 30 },
  { text: "Desenează un monstru cu părul făcut din spaghete!", seconds: 30 },
  { text: "Desenează un monstru care se ascunde sub pat dar are picioare prea mari!", seconds: 30 },
  { text: "Desenează un monstru care face baloane de săpun din nas!", seconds: 30 },
  { text: "Desenează un monstru cu dinți de vată de zahăr!", seconds: 30 },
  { text: "Desenează un monstru care se sperie de propria umbră!", seconds: 30 },
  { text: "Desenează un monstru cu 3 brațe, fiecare ținând o înghețată!", seconds: 30 },
  { text: "Desenează un monstru care mănâncă doar sarmale!", seconds: 30 },
  { text: "Desenează un monstru care strănută confetti!", seconds: 30 },
  { text: "Desenează un monstru cu urechi de elefant și coadă de pisică!", seconds: 30 },
  { text: "Desenează un monstru care poartă papuci de iepuraș!", seconds: 30 },
  { text: "Desenează un monstru care trăiește într-un dulap plin cu jucării!", seconds: 30 },
  { text: "Desenează un monstru care cântă la chitară cu 3 coarde rupte!", seconds: 30 },
  { text: "Desenează un monstru cu o singură sprânceană uriașă!", seconds: 30 },
  { text: "Desenează un monstru care colecționează nasturi colorați!", seconds: 30 },
  { text: "Desenează un monstru care se piaptănă cu o furculiță!", seconds: 30 },
  { text: "Desenează un monstru care doarme atârnat cu capul în jos, ca un liliac!", seconds: 30 },

  { text: "Desenează o pisică ce conduce un tractor!", seconds: 30 },
  { text: "Desenează un câine care poartă ochelari de soare și surfează!", seconds: 30 },
  { text: "Desenează o girafă cu gâtul înnodat!", seconds: 30 },
  { text: "Desenează un elefant care face baloane din trompă!", seconds: 30 },
  { text: "Desenează o broască țestoasă cu rachete la carapace!", seconds: 30 },
  { text: "Desenează un urs care coace prăjituri!", seconds: 30 },
  { text: "Desenează o veveriță cu o coadă de trei ori mai mare decât ea!", seconds: 30 },
  { text: "Desenează un iepure care joacă fotbal cu un morcov!", seconds: 30 },
  { text: "Desenează o zebră cu dungi în carouri!", seconds: 30 },
  { text: "Desenează un leu cu coama făcută din baloane!", seconds: 30 },
  { text: "Desenează o vacă ce zboară cu o umbrelă!", seconds: 30 },
  { text: "Desenează un porc care cântă la pian!", seconds: 30 },
  { text: "Desenează un cangur cu buzunarul plin de înghețată!", seconds: 30 },
  { text: "Desenează o cămilă cu 5 cocoașe!", seconds: 30 },
  { text: "Desenează un papagal care vorbește doar în rime!", seconds: 30 },
  { text: "Desenează o maimuță care se dă cu skateboard-ul!", seconds: 30 },
  { text: "Desenează un rechin cu papion și servietă!", seconds: 30 },
  { text: "Desenează o pinguină care poartă șapcă de baseball!", seconds: 30 },
  { text: "Desenează un liliac care se teme de întuneric!", seconds: 30 },
  { text: "Desenează o albină cu o pălărie de petrecere!", seconds: 30 },

  { text: "Desenează un extraterestru care colecționează pietricele de pe Pământ!", seconds: 30 },
  { text: "Desenează o farfurie zburătoare făcută din brânză!", seconds: 30 },
  { text: "Desenează un astronaut care a uitat casca acasă!", seconds: 30 },
  { text: "Desenează o planetă cu inele din acadele!", seconds: 30 },
  { text: "Desenează un extraterestru cu 2 capete care sunt cei mai buni prieteni!", seconds: 30 },
  { text: "Desenează o rachetă construită din cutii de carton!", seconds: 30 },
  { text: "Desenează un extraterestru verde care adoră mămăliga!", seconds: 30 },
  { text: "Desenează o stea căzătoare care s-a rătăcit pe Pământ!", seconds: 30 },
  { text: "Desenează o lună cu față zâmbitoare și coșuri!", seconds: 30 },
  { text: "Desenează un extraterestru care încearcă să învețe să meargă pe role!", seconds: 30 },
  { text: "Desenează un robot spațial care culege flori!", seconds: 30 },
  { text: "Desenează o cometă cu coadă de curcubeu!", seconds: 30 },
  { text: "Desenează un extraterestru speriat de un fluture!", seconds: 30 },
  { text: "Desenează o navă spațială pilotată de un pisoi!", seconds: 30 },

  { text: "Desenează un robot care adoră să danseze breakdance!", seconds: 30 },
  { text: "Desenează un robot de bucătărie care arde tot ce gătește!", seconds: 30 },
  { text: "Desenează un robot cu antene care prind doar posturi de desene animate!", seconds: 30 },
  { text: "Desenează un robot care plânge cu ulei în loc de lacrimi!", seconds: 30 },
  { text: "Desenează un robot uriaș construit din piese de Lego!", seconds: 30 },
  { text: "Desenează un robot de companie pentru un pește auriu!", seconds: 30 },
  { text: "Desenează un robot care se sperie de furtuni!", seconds: 30 },
  { text: "Desenează un robot cu roți de bicicletă în loc de picioare!", seconds: 30 },
  { text: "Desenează un robot grădinar care udă florile cu suc!", seconds: 30 },
  { text: "Desenează un robot minuscul care trăiește într-un ceas!", seconds: 30 },
  { text: "Desenează un robot care colecționează șuruburi ruginite!", seconds: 30 },
  { text: "Desenează un robot ce se crede câine și latră!", seconds: 30 },
  { text: "Desenează un robot care face bule de săpun în loc de fum!", seconds: 30 },
  { text: "Desenează un robot care se îmbracă în costum de dinozaur!", seconds: 30 },

  { text: "Desenează un dinozaur care își perie dinții cu o mătură!", seconds: 30 },
  { text: "Desenează un dinozaur minuscul, cât o pisică!", seconds: 30 },
  { text: "Desenează un dinozaur care poartă rucsac de școală!", seconds: 30 },
  { text: "Desenează un dinozaur cu pene colorate ca un curcubeu!", seconds: 30 },
  { text: "Desenează un dinozaur care se joacă baschet cu o minge uriașă!", seconds: 30 },
  { text: "Desenează un dinozaur speriat de un șoricel!", seconds: 30 },
  { text: "Desenează un dinozaur care cântă la tobe cu coada!", seconds: 30 },
  { text: "Desenează un dinozaur cu ochelari de citit!", seconds: 30 },
  { text: "Desenează un dinozaur care înoată cu colac de cauciuc!", seconds: 30 },
  { text: "Desenează un dinozaur care poartă o eșarfă foarte, foarte lungă!", seconds: 30 },

  { text: "Desenează o pizza cu picioare care fuge de tine!", seconds: 30 },
  { text: "Desenează un hamburger cât o casă!", seconds: 30 },
  { text: "Desenează o înghețată care se plimbă cu bicicleta!", seconds: 30 },
  { text: "Desenează un covrig cu ochi și zâmbet!", seconds: 30 },
  { text: "Desenează un tort care explodează cu confetti!", seconds: 30 },
  { text: "Desenează o banană deghizată în super-erou!", seconds: 30 },
  { text: "Desenează un morcov care poartă coroană de rege!", seconds: 30 },
  { text: "Desenează o gogoașă cu 100 de sprinkles!", seconds: 30 },
  { text: "Desenează un castravete care cântă la microfon!", seconds: 30 },
  { text: "Desenează o prăjitură cu picioare de păianjen!", seconds: 30 },
  { text: "Desenează un ou prăjit care poartă pălărie de bucătar!", seconds: 30 },
  { text: "Desenează o ciupercă gigantă cu ferestre și ușă, ca o căsuță!", seconds: 30 },
  { text: "Desenează un ardei gras care face karate!", seconds: 30 },
  { text: "Desenează o vată de zahăr în formă de nor furios!", seconds: 30 },
  { text: "Desenează un măr cu un vierme prieten, nu dușman!", seconds: 30 },
  { text: "Desenează o clătită care zboară ca un frisbee!", seconds: 30 },

  { text: "Desenează o mașină cu roți de brânză!", seconds: 30 },
  { text: "Desenează un tren care merge pe nori!", seconds: 30 },
  { text: "Desenează o barcă construită din pantofi vechi!", seconds: 30 },
  { text: "Desenează un avion cu aripi de fluture!", seconds: 30 },
  { text: "Desenează un submarin în formă de pește uriaș!", seconds: 30 },
  { text: "Desenează o bicicletă cu trei roți în față și una în spate!", seconds: 30 },
  { text: "Desenează un tractor condus de o găină!", seconds: 30 },
  { text: "Desenează o mașină de pompieri roz, cu sirenă care cântă!", seconds: 30 },
  { text: "Desenează un balon cu aer cald în formă de dovleac!", seconds: 30 },
  { text: "Desenează o trotinetă cu motor de rachetă!", seconds: 30 },
  { text: "Desenează un autobuz școlar plin cu maimuțe!", seconds: 30 },
  { text: "Desenează un elicopter cu elice făcute din creioane colorate!", seconds: 30 },
  { text: "Desenează o săniuță trasă de pinguini!", seconds: 30 },
  { text: "Desenează un camion de gunoi care miroase a flori!", seconds: 30 },

  { text: "Desenează un super-erou a cărui superputere e să facă cea mai tare gogoașă!", seconds: 30 },
  { text: "Desenează o super-eroină care zboară cu ajutorul unei umbrele!", seconds: 30 },
  { text: "Desenează un pirat care se teme de apă!", seconds: 30 },
  { text: "Desenează un cavaler cu armură făcută din carton!", seconds: 30 },
  { text: "Desenează o prințesă care preferă noroiul în loc de rochii!", seconds: 30 },
  { text: "Desenează un vrăjitor care își pierde mereu bagheta!", seconds: 30 },
  { text: "Desenează un ninja care se împiedică de propriile picioare!", seconds: 30 },
  { text: "Desenează un cowboy care călărește o gâscă!", seconds: 30 },
  { text: "Desenează un detectiv cu lupă și mustață falsă!", seconds: 30 },
  { text: "Desenează un super-erou al cărui costum e din pijamale!", seconds: 30 },
  { text: "Desenează un spion care se ascunde într-un ghiveci de flori!", seconds: 30 },
  { text: "Desenează un rege care domnește peste un regat de jucării!", seconds: 30 },
  { text: "Desenează un explorator pierdut într-o pădure de bomboane!", seconds: 30 },
  { text: "Desenează un magician a cărui pălărie e plină cu iepurași ce nu vor să iasă!", seconds: 30 },

  { text: "Desenează un dragon care se teme de foc!", seconds: 30 },
  { text: "Desenează un unicorn cu coama făcută din vată de zahăr!", seconds: 30 },
  { text: "Desenează o zână care a pierdut una dintre aripi!", seconds: 30 },
  { text: "Desenează un elf care colecționează pantofi ciudați!", seconds: 30 },
  { text: "Desenează un troll simpatic care adoră florile!", seconds: 30 },
  { text: "Desenează o sirenă cu coadă în carouri!", seconds: 30 },
  { text: "Desenează un pitic care trăiește într-o ciupercă uriașă!", seconds: 30 },
  { text: "Desenează un centaur care participă la o cursă de biciclete!", seconds: 30 },
  { text: "Desenează o fantomă care se sperie de întuneric!", seconds: 30 },
  { text: "Desenează un yeti care se topește la soare!", seconds: 30 },
  { text: "Desenează un vampir vegetarian care adoră usturoiul!", seconds: 30 },
  { text: "Desenează un balaur cu două capete, unul vesel și unul somnoros!", seconds: 30 },
  { text: "Desenează un spiriduș care șterpelește șosete!", seconds: 30 },
  { text: "Desenează o hidră cu 3 capete, toate purtând aceeași pălărie caraghioasă!", seconds: 30 },
  { text: "Desenează un grifon cu aripi de fluture!", seconds: 30 },
  { text: "Desenează un gnom de grădină care prinde viață noaptea!", seconds: 30 },

  { text: "Desenează un ceas cu picioare care fuge de tine!", seconds: 30 },
  { text: "Desenează o umbrelă care zboară ca un elicopter!", seconds: 30 },
  { text: "Desenează un aspirator care mănâncă tot ce vede!", seconds: 30 },
  { text: "Desenează o pernă cu față și zâmbet mare!", seconds: 30 },
  { text: "Desenează un scaun cu roți care face curse!", seconds: 30 },
  { text: "Desenează o oglindă caraghioasă care te face să arăți ca o broască!", seconds: 30 },
  { text: "Desenează un termos care scoate aburi în formă de inimioare!", seconds: 30 },
  { text: "Desenează o carte care sare din raft și zboară prin cameră!", seconds: 30 },
  { text: "Desenează un telefon vechi cu picioare de păianjen!", seconds: 30 },
  { text: "Desenează o lampă care visează să fie stea!", seconds: 30 },
  { text: "Desenează un fierăstrău care taie doar plăcinte!", seconds: 30 },
  { text: "Desenează o periuță de dinți care se plictisește de dinți!", seconds: 30 },
  { text: "Desenează un ghiozdan care mănâncă mereu temele!", seconds: 30 },
  { text: "Desenează o pereche de șosete care nu vor să stea împreună!", seconds: 30 },

  { text: "Desenează un nor care plânge lapte în loc de ploaie!", seconds: 30 },
  { text: "Desenează un curcubeu care se rostogolește ca o roată!", seconds: 30 },
  { text: "Desenează un soare cu ochelari de soare!", seconds: 30 },
  { text: "Desenează un fulg de nea uriaș, cât o mașină!", seconds: 30 },
  { text: "Desenează un vulcan care erupe înghețată!", seconds: 30 },
  { text: "Desenează un copac cu fructe care vorbesc!", seconds: 30 },
  { text: "Desenează o floare care cântă când bate vântul!", seconds: 30 },

  { text: "Desenează o pereche de pantofi care aleargă singuri!", seconds: 30 },
  { text: "Desenează o pălărie atât de înaltă încât ajunge la nori!", seconds: 30 },
  { text: "Desenează o eșarfă atât de lungă încât se înfășoară de 10 ori în jurul gâtului!", seconds: 30 },
  { text: "Desenează niște ochelari cu ștergătoare de parbriz!", seconds: 30 },
  { text: "Desenează o mănușă cu degete de mărimi diferite!", seconds: 30 },
  { text: "Desenează o cravată vie care se mișcă singură!", seconds: 30 },
  { text: "Desenează o rochie făcută din frunze de toamnă!", seconds: 30 },
  { text: "Desenează niște ghete de cauciuc pentru sărit în bălți uriașe!", seconds: 30 },
  { text: "Desenează o coroană din creioane colorate!", seconds: 30 },
  { text: "Desenează un rucsac cu propriul lui creier!", seconds: 30 },

  { text: "Desenează un monstru care râgâie curcubeu!", seconds: 30 },
  { text: "Desenează un balon care se dezumflă făcând cel mai amuzant sunet!", seconds: 30 },
  { text: "Desenează pe cineva care strănută atât de tare încât zboară pe spate!", seconds: 30 },
  { text: "Desenează un extraterestru care comunică doar prin sughițuri!", seconds: 30 },
  { text: "Desenează un dragon care scoate pe nas fum cu miros de brânză!", seconds: 30 },
  { text: "Desenează un robot care trage vânturi cu aburi colorați!", seconds: 30 },
  { text: "Desenează cea mai mare bășică de muci din lume!", seconds: 30 },
  { text: "Desenează un monstru care se scobește în nas și găsește o comoară!", seconds: 30 },
  { text: "Desenează un elefant care strănută atât de tare încât suflă pălăriile tuturor!", seconds: 30 },
  { text: "Desenează un personaj care râgâie literele alfabetului!", seconds: 30 },
  { text: "Desenează un porc care se rostogolește vesel prin noroi!", seconds: 30 },
  { text: "Desenează un câine care doarme sforăind ca un tractor!", seconds: 30 },
  { text: "Desenează un monstru care își suflă nasul într-o pânză de păianjen!", seconds: 30 },
  { text: "Desenează cel mai puturos pantof din lume, cu un nor verde deasupra!", seconds: 30 },

  { text: "Desenează-te pe tine peste 100 de ani!", seconds: 30 },
  { text: "Desenează un frate sau o soră transformați în super-erou obosit!", seconds: 30 },
  { text: "Desenează-ți bunica zburând cu mătura, ca o vrăjitoare simpatică!", seconds: 30 },
  { text: "Desenează-te pe tine gigant, mai mare decât blocul!", seconds: 30 },
  { text: "Desenează-ți mama sau tatăl ca un supererou al gospodăriei!", seconds: 30 },
  { text: "Desenează-te pe tine ca rege sau regină al camerei tale!", seconds: 30 },
  { text: "Desenează-ți cel mai bun prieten ca personaj de desene animate!", seconds: 30 },

  { text: "Desenează o stea de mare care poartă ochelari de soare!", seconds: 30 },
  { text: "Desenează un pește clovn cu pălărie de petrecere!", seconds: 30 },
  { text: "Desenează o meduză care plutește ca un balon!", seconds: 30 },
  { text: "Desenează un crab care merge cu role!", seconds: 30 },
  { text: "Desenează un delfin care sare printr-un cerc de săpun!", seconds: 30 },
  { text: "Desenează o caracatiță care cântă la opt tobe deodată!", seconds: 30 },
  { text: "Desenează un pește-spadă care se bărbierește!", seconds: 30 },
  { text: "Desenează un homar roșu care poartă papion!", seconds: 30 },
  { text: "Desenează un cal de mare cât o balenă!", seconds: 30 },
  { text: "Desenează o scoică ce zâmbește larg!", seconds: 30 },

  { text: "Desenează un fluture cu aripi în carouri!", seconds: 30 },
  { text: "Desenează o gărgăriță cu 20 de puncte colorate!", seconds: 30 },
  { text: "Desenează o omidă care poartă o sută de pantofi!", seconds: 30 },
  { text: "Desenează un greiere care cântă la vioară!", seconds: 30 },
  { text: "Desenează o furnică ce cară un sandviș uriaș!", seconds: 30 },
  { text: "Desenează o libelulă cu aripi de curcubeu!", seconds: 30 },
  { text: "Desenează un păianjen care tricotează o pânză roz!", seconds: 30 },
  { text: "Desenează o albină obosită care doarme într-o floare!", seconds: 30 },

  { text: "Desenează o minge de fotbal cu față speriată!", seconds: 30 },
  { text: "Desenează o rachetă de tenis care joacă singură!", seconds: 30 },
  { text: "Desenează o bicicletă cu roți pătrate!", seconds: 30 },
  { text: "Desenează un skateboard care zboară!", seconds: 30 },
  { text: "Desenează o minge de baschet care sare până la lună!", seconds: 30 },
  { text: "Desenează o coardă de sărit ce se mișcă singură!", seconds: 30 },
  { text: "Desenează o trambulină uriașă în formă de pizza!", seconds: 30 },
  { text: "Desenează niște patine cu rotile care aleargă fără picioare!", seconds: 30 },

  { text: "Desenează o umbrelă care urăște ploaia!", seconds: 30 },
  { text: "Desenează o lingură și o furculiță care dansează împreună!", seconds: 30 },
  { text: "Desenează un pahar care râde cu suc pe gură!", seconds: 30 },
  { text: "Desenează o pernă care sforăie tare!", seconds: 30 },
  { text: "Desenează un ceainic care fluieră o melodie!", seconds: 30 },
  { text: "Desenează o oglindă care se piaptănă singură!", seconds: 30 },
  { text: "Desenează un covor care zboară doar puțin, aproape de podea!", seconds: 30 },
  { text: "Desenează un ceas deșteptător furios dimineața!", seconds: 30 },
  { text: "Desenează o cutie de creioane care se ceartă cine e cel mai colorat!", seconds: 30 },
  { text: "Desenează un termometru care tremură de frig!", seconds: 30 },

  { text: "Desenează un spiriduș de zăpadă cu nas de morcov!", seconds: 30 },
  { text: "Desenează un pui de dragon care strănută scântei!", seconds: 30 },
  { text: "Desenează o zână a dulciurilor cu aripi de acadea!", seconds: 30 },
  { text: "Desenează un gnom pitic care poartă o pălărie cât el de mare!", seconds: 30 },
  { text: "Desenează un pui de unicorn care încă învață să zboare!", seconds: 30 },
  { text: "Desenează un spiriduș verde ce trăiește într-o ghindă!", seconds: 30 },
  { text: "Desenează o broscuță fermecată cu coroană strâmbă!", seconds: 30 },
  { text: "Desenează un ursuleț de pluș care prinde viață noaptea!", seconds: 30 },

  { text: "Desenează un nor cu ochelari și mustață!", seconds: 30 },
  { text: "Desenează un fulger care face cu ochiul!", seconds: 30 },
  { text: "Desenează o stea care cântă la chitară!", seconds: 30 },
  { text: "Desenează un vânt vesel care suflă pălăriile tuturor!", seconds: 30 },
  { text: "Desenează o ploaie de bomboane colorate!", seconds: 30 },
  { text: "Desenează o lună care poartă căciulă de iarnă!", seconds: 30 },

  { text: "Desenează o înghețată care se topește de râs!", seconds: 30 },
  { text: "Desenează un ardei iute cu față furioasă!", seconds: 30 },
  { text: "Desenează o lămâie acră care face o grimasă!", seconds: 30 },
  { text: "Desenează un fursec cu ochi mari și gură zâmbitoare!", seconds: 30 },
  { text: "Desenează o portocală care joacă baschet!", seconds: 30 },
  { text: "Desenează un pahar de limonadă cu paie strâmbă!", seconds: 30 },

  { text: "Desenează o bufniță care poartă ochelari de citit!", seconds: 30 },
  { text: "Desenează un arici cu baloane în loc de țepi!", seconds: 30 },
  { text: "Desenează o rață cu cizme de ploaie galbene!", seconds: 30 },
  { text: "Desenează un cal care sare peste un curcubeu!", seconds: 30 },
];

window.DRAW_PROMPTS_EN = [
  { text: "Draw a monster that only eats broccoli!", seconds: 30 },
  { text: "Draw your dream pet, as weird as possible!", seconds: 30 },
  { text: "Draw an alien that just landed in your yard!", seconds: 30 },
  { text: "Draw the biggest sandwich in the world!", seconds: 30 },
  { text: "Draw yourself as a superhero!", seconds: 30 },
  { text: "Draw a dinosaur wearing sneakers!", seconds: 30 },
  { text: "Draw a pizza with the weirdest toppings!", seconds: 30 },
  { text: "Draw a robot doing its homework!", seconds: 30 },
  { text: "Draw a fish that learned to fly!", seconds: 30 },
  { text: "Draw the funniest hat in the world!", seconds: 30 },

  { text: "Draw a monster afraid of the dark that sleeps with the lamp on!", seconds: 30 },
  { text: "Draw a monster with 100 eyes that can't see a thing!", seconds: 30 },
  { text: "Draw a monster that collects lost socks!", seconds: 30 },
  { text: "Draw a monster that cries when it hears sad music!", seconds: 30 },
  { text: "Draw a monster with hair made of spaghetti!", seconds: 30 },
  { text: "Draw a monster hiding under the bed with feet too big to fit!", seconds: 30 },
  { text: "Draw a monster blowing soap bubbles out of its nose!", seconds: 30 },
  { text: "Draw a monster with cotton candy teeth!", seconds: 30 },
  { text: "Draw a monster scared of its own shadow!", seconds: 30 },
  { text: "Draw a monster with 3 arms, each holding an ice cream!", seconds: 30 },
  { text: "Draw a monster that only eats stuffed cabbage rolls!", seconds: 30 },
  { text: "Draw a monster that sneezes confetti!", seconds: 30 },
  { text: "Draw a monster with elephant ears and a cat tail!", seconds: 30 },
  { text: "Draw a monster wearing bunny slippers!", seconds: 30 },
  { text: "Draw a monster that lives in a closet full of toys!", seconds: 30 },
  { text: "Draw a monster playing guitar with 3 broken strings!", seconds: 30 },
  { text: "Draw a monster with one giant eyebrow!", seconds: 30 },
  { text: "Draw a monster that collects colorful buttons!", seconds: 30 },
  { text: "Draw a monster combing its hair with a fork!", seconds: 30 },
  { text: "Draw a monster that sleeps hanging upside down, like a bat!", seconds: 30 },

  { text: "Draw a cat driving a tractor!", seconds: 30 },
  { text: "Draw a dog wearing sunglasses and surfing!", seconds: 30 },
  { text: "Draw a giraffe with its neck tied in a knot!", seconds: 30 },
  { text: "Draw an elephant blowing bubbles from its trunk!", seconds: 30 },
  { text: "Draw a turtle with rockets on its shell!", seconds: 30 },
  { text: "Draw a bear baking cookies!", seconds: 30 },
  { text: "Draw a squirrel with a tail three times bigger than itself!", seconds: 30 },
  { text: "Draw a rabbit playing soccer with a carrot!", seconds: 30 },
  { text: "Draw a zebra with checkered stripes!", seconds: 30 },
  { text: "Draw a lion with a mane made of balloons!", seconds: 30 },
  { text: "Draw a cow flying with an umbrella!", seconds: 30 },
  { text: "Draw a pig playing piano!", seconds: 30 },
  { text: "Draw a kangaroo with its pouch full of ice cream!", seconds: 30 },
  { text: "Draw a camel with 5 humps!", seconds: 30 },
  { text: "Draw a parrot that only speaks in rhymes!", seconds: 30 },
  { text: "Draw a monkey riding a skateboard!", seconds: 30 },
  { text: "Draw a shark with a bow tie and a briefcase!", seconds: 30 },
  { text: "Draw a penguin wearing a baseball cap!", seconds: 30 },
  { text: "Draw a bat that's afraid of the dark!", seconds: 30 },
  { text: "Draw a bee wearing a party hat!", seconds: 30 },

  { text: "Draw an alien that collects pebbles from Earth!", seconds: 30 },
  { text: "Draw a flying saucer made of cheese!", seconds: 30 },
  { text: "Draw an astronaut who forgot their helmet at home!", seconds: 30 },
  { text: "Draw a planet with rings made of lollipops!", seconds: 30 },
  { text: "Draw a 2-headed alien where both heads are best friends!", seconds: 30 },
  { text: "Draw a rocket built out of cardboard boxes!", seconds: 30 },
  { text: "Draw a green alien who loves mashed potatoes!", seconds: 30 },
  { text: "Draw a shooting star that got lost on Earth!", seconds: 30 },
  { text: "Draw a moon with a smiling face and freckles!", seconds: 30 },
  { text: "Draw an alien trying to learn how to rollerskate!", seconds: 30 },
  { text: "Draw a space robot picking flowers!", seconds: 30 },
  { text: "Draw a comet with a rainbow tail!", seconds: 30 },
  { text: "Draw an alien scared of a butterfly!", seconds: 30 },
  { text: "Draw a spaceship piloted by a kitten!", seconds: 30 },

  { text: "Draw a robot that loves breakdancing!", seconds: 30 },
  { text: "Draw a kitchen robot that burns everything it cooks!", seconds: 30 },
  { text: "Draw a robot with antennas that only pick up cartoon channels!", seconds: 30 },
  { text: "Draw a robot that cries oil instead of tears!", seconds: 30 },
  { text: "Draw a giant robot built out of Lego bricks!", seconds: 30 },
  { text: "Draw a companion robot for a goldfish!", seconds: 30 },
  { text: "Draw a robot that's afraid of thunderstorms!", seconds: 30 },
  { text: "Draw a robot with bicycle wheels instead of legs!", seconds: 30 },
  { text: "Draw a gardener robot that waters flowers with juice!", seconds: 30 },
  { text: "Draw a tiny robot that lives inside a clock!", seconds: 30 },
  { text: "Draw a robot that collects rusty screws!", seconds: 30 },
  { text: "Draw a robot that thinks it's a dog and barks!", seconds: 30 },
  { text: "Draw a robot that blows soap bubbles instead of smoke!", seconds: 30 },
  { text: "Draw a robot dressed up in a dinosaur costume!", seconds: 30 },

  { text: "Draw a dinosaur brushing its teeth with a broom!", seconds: 30 },
  { text: "Draw a tiny dinosaur, as small as a cat!", seconds: 30 },
  { text: "Draw a dinosaur wearing a school backpack!", seconds: 30 },
  { text: "Draw a dinosaur with rainbow-colored feathers!", seconds: 30 },
  { text: "Draw a dinosaur playing basketball with a giant ball!", seconds: 30 },
  { text: "Draw a dinosaur scared of a tiny mouse!", seconds: 30 },
  { text: "Draw a dinosaur playing drums with its tail!", seconds: 30 },
  { text: "Draw a dinosaur wearing reading glasses!", seconds: 30 },
  { text: "Draw a dinosaur swimming with a pool float!", seconds: 30 },
  { text: "Draw a dinosaur wearing a super, super long scarf!", seconds: 30 },

  { text: "Draw a pizza with legs running away from you!", seconds: 30 },
  { text: "Draw a hamburger as big as a house!", seconds: 30 },
  { text: "Draw an ice cream cone riding a bicycle!", seconds: 30 },
  { text: "Draw a pretzel with eyes and a smile!", seconds: 30 },
  { text: "Draw a cake exploding with confetti!", seconds: 30 },
  { text: "Draw a banana disguised as a superhero!", seconds: 30 },
  { text: "Draw a carrot wearing a king's crown!", seconds: 30 },
  { text: "Draw a donut with 100 sprinkles!", seconds: 30 },
  { text: "Draw a cucumber singing into a microphone!", seconds: 30 },
  { text: "Draw a cupcake with spider legs!", seconds: 30 },
  { text: "Draw a fried egg wearing a chef's hat!", seconds: 30 },
  { text: "Draw a giant mushroom with windows and a door, like a little house!", seconds: 30 },
  { text: "Draw a bell pepper doing karate!", seconds: 30 },
  { text: "Draw cotton candy shaped like an angry cloud!", seconds: 30 },
  { text: "Draw an apple with a friendly worm, not an enemy!", seconds: 30 },
  { text: "Draw a pancake flying like a frisbee!", seconds: 30 },

  { text: "Draw a car with cheese wheels!", seconds: 30 },
  { text: "Draw a train riding on clouds!", seconds: 30 },
  { text: "Draw a boat built out of old shoes!", seconds: 30 },
  { text: "Draw a plane with butterfly wings!", seconds: 30 },
  { text: "Draw a submarine shaped like a giant fish!", seconds: 30 },
  { text: "Draw a bicycle with three wheels in front and one in back!", seconds: 30 },
  { text: "Draw a tractor driven by a chicken!", seconds: 30 },
  { text: "Draw a pink fire truck with a siren that sings!", seconds: 30 },
  { text: "Draw a hot air balloon shaped like a pumpkin!", seconds: 30 },
  { text: "Draw a scooter with a rocket engine!", seconds: 30 },
  { text: "Draw a school bus full of monkeys!", seconds: 30 },
  { text: "Draw a helicopter with propellers made of colored pencils!", seconds: 30 },
  { text: "Draw a sled pulled by penguins!", seconds: 30 },
  { text: "Draw a garbage truck that smells like flowers!", seconds: 30 },

  { text: "Draw a superhero whose superpower is making the best donuts!", seconds: 30 },
  { text: "Draw a superheroine who flies using an umbrella!", seconds: 30 },
  { text: "Draw a pirate who's afraid of water!", seconds: 30 },
  { text: "Draw a knight with armor made of cardboard!", seconds: 30 },
  { text: "Draw a princess who prefers mud over dresses!", seconds: 30 },
  { text: "Draw a wizard who always loses his wand!", seconds: 30 },
  { text: "Draw a ninja who trips over his own feet!", seconds: 30 },
  { text: "Draw a cowboy riding a goose!", seconds: 30 },
  { text: "Draw a detective with a magnifying glass and a fake mustache!", seconds: 30 },
  { text: "Draw a superhero whose costume is made of pajamas!", seconds: 30 },
  { text: "Draw a spy hiding inside a flowerpot!", seconds: 30 },
  { text: "Draw a king ruling over a kingdom of toys!", seconds: 30 },
  { text: "Draw an explorer lost in a forest of candy!", seconds: 30 },
  { text: "Draw a magician whose hat is full of rabbits that won't come out!", seconds: 30 },

  { text: "Draw a dragon that's afraid of fire!", seconds: 30 },
  { text: "Draw a unicorn with a mane made of cotton candy!", seconds: 30 },
  { text: "Draw a fairy who lost one of her wings!", seconds: 30 },
  { text: "Draw an elf who collects weird shoes!", seconds: 30 },
  { text: "Draw a friendly troll who loves flowers!", seconds: 30 },
  { text: "Draw a mermaid with a checkered tail!", seconds: 30 },
  { text: "Draw a dwarf who lives inside a giant mushroom!", seconds: 30 },
  { text: "Draw a centaur competing in a bike race!", seconds: 30 },
  { text: "Draw a ghost that's afraid of the dark!", seconds: 30 },
  { text: "Draw a yeti melting in the sun!", seconds: 30 },
  { text: "Draw a vegetarian vampire who loves garlic!", seconds: 30 },
  { text: "Draw a 2-headed dragon, one happy and one sleepy!", seconds: 30 },
  { text: "Draw a goblin that steals socks!", seconds: 30 },
  { text: "Draw a 3-headed hydra, all wearing the same silly hat!", seconds: 30 },
  { text: "Draw a griffin with butterfly wings!", seconds: 30 },
  { text: "Draw a garden gnome that comes to life at night!", seconds: 30 },

  { text: "Draw a clock with legs running away from you!", seconds: 30 },
  { text: "Draw an umbrella that flies like a helicopter!", seconds: 30 },
  { text: "Draw a vacuum cleaner that eats everything it sees!", seconds: 30 },
  { text: "Draw a pillow with a face and a big smile!", seconds: 30 },
  { text: "Draw a wheelchair that races!", seconds: 30 },
  { text: "Draw a funny mirror that makes you look like a frog!", seconds: 30 },
  { text: "Draw a thermos puffing out heart-shaped steam!", seconds: 30 },
  { text: "Draw a book that jumps off the shelf and flies around the room!", seconds: 30 },
  { text: "Draw an old telephone with spider legs!", seconds: 30 },
  { text: "Draw a lamp that dreams of being a star!", seconds: 30 },
  { text: "Draw a saw that only cuts pies!", seconds: 30 },
  { text: "Draw a toothbrush that's bored of teeth!", seconds: 30 },
  { text: "Draw a backpack that keeps eating your homework!", seconds: 30 },
  { text: "Draw a pair of socks that refuse to stay together!", seconds: 30 },

  { text: "Draw a cloud that cries milk instead of rain!", seconds: 30 },
  { text: "Draw a rainbow rolling along like a wheel!", seconds: 30 },
  { text: "Draw a sun wearing sunglasses!", seconds: 30 },
  { text: "Draw a giant snowflake, as big as a car!", seconds: 30 },
  { text: "Draw a volcano erupting ice cream!", seconds: 30 },
  { text: "Draw a tree with fruit that talks!", seconds: 30 },
  { text: "Draw a flower that sings when the wind blows!", seconds: 30 },

  { text: "Draw a pair of shoes that run by themselves!", seconds: 30 },
  { text: "Draw a hat so tall it reaches the clouds!", seconds: 30 },
  { text: "Draw a scarf so long it wraps around your neck 10 times!", seconds: 30 },
  { text: "Draw a pair of glasses with tiny windshield wipers!", seconds: 30 },
  { text: "Draw a glove with fingers of all different sizes!", seconds: 30 },
  { text: "Draw a necktie that's alive and moves on its own!", seconds: 30 },
  { text: "Draw a dress made of autumn leaves!", seconds: 30 },
  { text: "Draw rubber boots for jumping into giant puddles!", seconds: 30 },
  { text: "Draw a crown made of colored pencils!", seconds: 30 },
  { text: "Draw a backpack with its own brain!", seconds: 30 },

  { text: "Draw a monster burping a rainbow!", seconds: 30 },
  { text: "Draw a balloon deflating with the funniest sound ever!", seconds: 30 },
  { text: "Draw someone sneezing so hard they fly backwards!", seconds: 30 },
  { text: "Draw an alien that only communicates through hiccups!", seconds: 30 },
  { text: "Draw a dragon blowing cheese-scented smoke out its nose!", seconds: 30 },
  { text: "Draw a robot tooting colorful steam!", seconds: 30 },
  { text: "Draw the biggest booger bubble in the world!", seconds: 30 },
  { text: "Draw a monster picking its nose and finding treasure!", seconds: 30 },
  { text: "Draw an elephant sneezing so hard it blows everyone's hats off!", seconds: 30 },
  { text: "Draw a character burping out the letters of the alphabet!", seconds: 30 },
  { text: "Draw a pig happily rolling around in mud!", seconds: 30 },
  { text: "Draw a dog sleeping and snoring like a tractor!", seconds: 30 },
  { text: "Draw a monster blowing its nose into a spider web!", seconds: 30 },
  { text: "Draw the smelliest shoe in the world, with a green cloud above it!", seconds: 30 },

  { text: "Draw yourself 100 years from now!", seconds: 30 },
  { text: "Draw a brother or sister turned into a tired superhero!", seconds: 30 },
  { text: "Draw your grandma flying on a broom like a friendly witch!", seconds: 30 },
  { text: "Draw yourself as a giant, bigger than your apartment building!", seconds: 30 },
  { text: "Draw your mom or dad as a household superhero!", seconds: 30 },
  { text: "Draw yourself as the king or queen of your room!", seconds: 30 },
  { text: "Draw your best friend as a cartoon character!", seconds: 30 },

  { text: "Draw a starfish wearing sunglasses!", seconds: 30 },
  { text: "Draw a clownfish wearing a party hat!", seconds: 30 },
  { text: "Draw a jellyfish floating like a balloon!", seconds: 30 },
  { text: "Draw a crab rollerskating!", seconds: 30 },
  { text: "Draw a dolphin jumping through a soap bubble ring!", seconds: 30 },
  { text: "Draw an octopus playing eight drums at once!", seconds: 30 },
  { text: "Draw a swordfish shaving!", seconds: 30 },
  { text: "Draw a red lobster wearing a bow tie!", seconds: 30 },
  { text: "Draw a seahorse as big as a whale!", seconds: 30 },
  { text: "Draw a seashell with a big smile!", seconds: 30 },

  { text: "Draw a butterfly with checkered wings!", seconds: 30 },
  { text: "Draw a ladybug with 20 colorful spots!", seconds: 30 },
  { text: "Draw a caterpillar wearing a hundred shoes!", seconds: 30 },
  { text: "Draw a cricket playing violin!", seconds: 30 },
  { text: "Draw an ant carrying a giant sandwich!", seconds: 30 },
  { text: "Draw a dragonfly with rainbow wings!", seconds: 30 },
  { text: "Draw a spider knitting a pink web!", seconds: 30 },
  { text: "Draw a tired bee sleeping inside a flower!", seconds: 30 },

  { text: "Draw a soccer ball with a scared face!", seconds: 30 },
  { text: "Draw a tennis racket playing all by itself!", seconds: 30 },
  { text: "Draw a bicycle with square wheels!", seconds: 30 },
  { text: "Draw a flying skateboard!", seconds: 30 },
  { text: "Draw a basketball bouncing all the way to the moon!", seconds: 30 },
  { text: "Draw a jump rope moving by itself!", seconds: 30 },
  { text: "Draw a giant trampoline shaped like a pizza!", seconds: 30 },
  { text: "Draw a pair of roller skates running with no feet in them!", seconds: 30 },

  { text: "Draw an umbrella that hates the rain!", seconds: 30 },
  { text: "Draw a spoon and a fork dancing together!", seconds: 30 },
  { text: "Draw a cup laughing with juice dribbling out!", seconds: 30 },
  { text: "Draw a pillow snoring loudly!", seconds: 30 },
  { text: "Draw a kettle whistling a tune!", seconds: 30 },
  { text: "Draw a mirror combing its own hair!", seconds: 30 },
  { text: "Draw a carpet that flies just a little, close to the floor!", seconds: 30 },
  { text: "Draw an angry alarm clock in the morning!", seconds: 30 },
  { text: "Draw a box of crayons arguing about who's the most colorful!", seconds: 30 },
  { text: "Draw a thermometer shivering with cold!", seconds: 30 },

  { text: "Draw a snow elf with a carrot nose!", seconds: 30 },
  { text: "Draw a baby dragon sneezing sparks!", seconds: 30 },
  { text: "Draw a candy fairy with lollipop wings!", seconds: 30 },
  { text: "Draw a tiny gnome wearing a hat as big as himself!", seconds: 30 },
  { text: "Draw a baby unicorn still learning to fly!", seconds: 30 },
  { text: "Draw a green pixie who lives inside an acorn!", seconds: 30 },
  { text: "Draw an enchanted little frog wearing a crooked crown!", seconds: 30 },
  { text: "Draw a teddy bear that comes to life at night!", seconds: 30 },

  { text: "Draw a cloud wearing glasses and a mustache!", seconds: 30 },
  { text: "Draw a lightning bolt winking!", seconds: 30 },
  { text: "Draw a star playing guitar!", seconds: 30 },
  { text: "Draw a happy wind blowing everyone's hats off!", seconds: 30 },
  { text: "Draw a rain of colorful candy!", seconds: 30 },
  { text: "Draw a moon wearing a winter hat!", seconds: 30 },

  { text: "Draw an ice cream cone melting from laughing so hard!", seconds: 30 },
  { text: "Draw a hot pepper with an angry face!", seconds: 30 },
  { text: "Draw a sour lemon making a scrunched-up face!", seconds: 30 },
  { text: "Draw a cookie with big eyes and a smiling mouth!", seconds: 30 },
  { text: "Draw an orange playing basketball!", seconds: 30 },
  { text: "Draw a glass of lemonade with a bent straw!", seconds: 30 },

  { text: "Draw an owl wearing reading glasses!", seconds: 30 },
  { text: "Draw a hedgehog with balloons instead of spikes!", seconds: 30 },
  { text: "Draw a duck wearing yellow rain boots!", seconds: 30 },
  { text: "Draw a horse jumping over a rainbow!", seconds: 30 },
];
