// Seed question bank (CAP-7). 200 kid-friendly interview questions in Romanian,
// written simple and funny for ages 6-10, per
// _bmad-output/specs/spec-interview-questions/question-content-guidelines.md.
// Sentence case here; the UI applies the all-caps display transform.
window.QUESTIONS = [
  // Ai prefera...
  "Ai prefera să ai coadă de dinozaur sau aripi de fluture?",
  "Ai prefera să mănânci o broscuță de ciocolată sau un vierme de jeleu?",
  "Ai prefera să ai un cățel robot sau o pisică ce vorbește?",
  "Ai prefera să sari ca un cangur sau să te miști ca un melc?",
  "Ai prefera să ai părul verde sau pielea albastră?",
  "Ai prefera să locuiești într-un castel de dulciuri sau într-o casă din Lego?",
  "Ai prefera să zbori ca o pasăre sau să înoți ca un pește?",
  "Ai prefera să ai o sută de baloane sau un singur balon cât o casă?",
  "Ai prefera să mănânci doar înghețată sau doar pizza toată viața?",
  "Ai prefera să ai un unicorn sau un dragon ca animal de companie?",
  "Ai prefera să râzi ca o hienă sau să vorbești ca o rață toată ziua?",
  "Ai prefera să ai degete lipicioase sau picioare care se lipesc de pereți?",
  "Ai prefera să dormi într-un hamac sau într-o cadă plină de perne?",
  "Ai prefera să ai o mașină zburătoare sau o bicicletă care înoată?",
  "Ai prefera să fii cel mai rapid din lume sau cel mai puternic din lume?",
  "Ai prefera să ai ochi de pisică sau urechi de iepure?",
  "Ai prefera să mănânci supă cu bețișoare sau înghețată cu furculița?",
  "Ai prefera să ai o casă pe roți sau o casă în copac?",
  "Ai prefera să te transformi în pisică sau în câine pentru o zi?",
  "Ai prefera să ai un robot care face temele sau unul care face curat?",
  "Ai prefera să sari în piscină îmbrăcat sau să mergi la ploaie fără umbrelă?",
  "Ai prefera să ai voce de robot sau voce de desen animat?",
  "Ai prefera să mănânci un ardei iute sau o lămâie întreagă?",
  "Ai prefera să te cațeri ca o maimuță sau să sari ca o broască?",
  "Ai prefera să ai o mie de jucării mici sau o jucărie uriașă?",
  "Ai prefera să dormi toată ziua sau să te joci toată noaptea?",
  "Ai prefera să ai o pălărie magică sau o baghetă magică?",
  "Ai prefera să te plimbi cu un elefant sau cu o girafă?",
  "Ai prefera să ai gheare de leu sau coadă de maimuță?",
  "Ai prefera să plutești prin aer sau să mergi pe sub apă?",

  // Asta sau asta
  "Dragon care strănută foc sau unicorn care râgâie curcubeu?",
  "Vampir cu sughiț sau zombi care sforăie ca un tractor?",
  "Ninja care chițăie sau pirat cu papagal care vorbește?",
  "Extraterestru cu picior de pui sau robot cu coadă de purcel?",
  "Monstru sub pat sau monstru în dulap?",
  "Supererou care uită tot sau super-ticălos căruia îi e frică de întuneric?",
  "Vrăjitor cu bot de rață sau samurai cu mustață de morsă?",
  "Yeti cu papuci roz sau Bigfoot cu fundiță la coadă?",
  "Fantomă care sughite sau schelet care zdrăngăne muzică?",
  "Rechin cu dinți de iepure sau crocodil cu solzi lipicioși?",
  "Uriaș care se împiedică mereu sau pitic care sare peste tot?",
  "Broscoi vorbitor sau pisică zburătoare?",
  "Pârț sonor sau râgâială uriașă?",
  "Nas de clovn sau urechi de măgar?",
  "Castel plutitor sau peșteră secretă?",
  "Bulgăre de zăpadă sau balon cu apă?",
  "Trambulină sau tobogan de apă?",
  "Sirenă cu coadă lipicioasă sau centaur cu copite de balerină?",
  "Cap de robot sau coadă de dragon?",
  "Pantofi care scârțâie sau haine care miros a brânză?",
  "Cântat de balenă sau urlat de lup?",
  "Mustață de pisică sau coadă de veveriță?",
  "Clovn haios sau magician care dă mereu greș?",
  "Prăjitură vorbitoare sau înghețată care cântă?",
  "Coadă de sirenă sau aripi de liliac?",
  "Cizme pline cu jeleu sau pline cu spumă?",
  "Castel de bomboane sau casă de prăjituri?",
  "Tun cu apă sau tun cu baloane?",
  "Robot care pârâie sau robot care sughite?",
  "Delfin vorbitor sau papagal glumeț?",

  // Imaginație
  "Ești invizibil chiar acum, ce faci primul lucru?",
  "Profesorul tău se transformă brusc într-un dinozaur, ce faci?",
  "Găsești o comoară îngropată în curte, ce faci cu ea?",
  "Îți cresc aripi chiar acum, unde zbori primul?",
  "Deschizi frigiderul și găsești un pinguin care dansează, ce faci?",
  "Te urci într-o mașină a timpului, unde mergi primul?",
  "Te trezești mic cât o furnică, ce faci primul lucru?",
  "Primești un dragon de companie chiar acum, cum îl cheamă?",
  "Te uiți sub pat și găsești un dragon care doarme, ce faci?",
  "Primești o superputere chiar acum, care e?",
  "Ești profesor pentru o zi, ce-i pui pe copii să facă?",
  "Primești un robot personal, ce-l pui să facă întâi?",
  "Te transformi într-un animal chiar acum, în care?",
  "Mergi la baie și cada e plină cu jeleu, ce faci?",
  "Trebuie să mănânci un singur fel de mâncare toată viața, ce alegi?",
  "Găsești o baghetă magică, ce faci cu ea prima dată?",
  "Ești căpitan de pirați, cum îți numești corabia?",
  "Animalele din curte încep să vorbească, pe care-l întrebi primul?",
  "Primești o insulă doar a ta, ce construiești pe ea?",
  "Ești supererou chiar acum, ce nume îți dai?",
  "Farfuria ta începe brusc să cânte la masă, ce faci?",
  "Școala ta primește un tobogan în loc de scări, îl folosești în fiecare zi?",
  "Te transformi într-un dinozaur chiar acum, în care?",
  "Camera ta se umple brusc cu o mie de baloane, ce faci?",
  "Te trezești în interiorul jocului tău video preferat, ce faci primul?",
  "Devii invizibil chiar la școală, ce faci primul lucru?",
  "Primești un animal uriaș ca prieten, care e?",
  "Deschizi ghiozdanul și găsești un pui de dragon înăuntru, ce faci?",
  "Zbori pe un covor magic chiar acum, unde te duci?",
  "Ești vrăjitor pentru o zi, ce vrajă faci prima?",
  "Primești un castel doar al tău, câte camere are?",
  "Un dinozaur apare în curtea ta, ce îl întrebi?",
  "Urci într-o rachetă chiar acum, pe ce planetă mergi?",
  "Sună la ușă și e un urs în pijamale, ce faci?",
  "Devii cel mai puternic om din lume pentru o zi, ce faci?",
  "Te uiți în oglindă și faci fețe ciudate fără să vrei, ce faci?",
  "Te muți să trăiești sub apă, cum arată casa ta?",
  "Toți colegii tăi vin la școală costumați în dinozauri, ce faci?",
  "Primești puterea de a opri timpul, ce faci cu ea?",
  "Te transformi într-un super-câine chiar acum, ce puteri ai?",

  // Cele mai haioase
  "Care e cel mai haios sunet pe care poți să-l faci?",
  "Ce ai pune pe pizza ca să fie cel mai ciudat?",
  "Care e cea mai haioasă față pe care o poți face acum?",
  "Ce nume amuzant ai da unui pește de companie?",
  "Care e cel mai ciudat vis pe care ți-l amintești?",
  "Care e cel mai haios lucru pe care l-a făcut animalul tău?",
  "Ce joc amuzant ai inventat vreodată?",
  "Care e cea mai ciudată mâncare pe care ai gustat-o?",
  "Ce miros ciudat ai simțit vreodată?",
  "Care e cea mai amuzantă glumă pe care o știi?",
  "Ce ai face dacă ai găsi un ou uriaș în curte?",
  "Care e cel mai amuzant costum pe care l-ai purtat?",
  "Ce cuvânt amuzant îți place să spui?",
  "Care e cel mai haios nume pe care l-ai putea da unui robot?",
  "Ce dans amuzant știi să faci?",
  "Care e cel mai ciudat lucru din buzunarul tău acum?",
  "Ce ai face dacă te-ai trezi cu coadă de maimuță?",
  "Care e cel mai haios zgomot pe care îl face casa ta noaptea?",
  "Ce ți s-a întâmplat amuzant la școală?",
  "Care e cea mai ciudată aromă de înghețată la care te gândești?",
  "Ce animal face cel mai amuzant sunet?",
  "Care e cel mai haios lucru pe care l-ai crezut când erai mic?",
  "Ce ai face dacă ți-ar vorbi jucăriile?",
  "Care e cea mai ciudată poreclă pe care ai avut-o?",
  "Ce ai face dacă ar ploua cu bomboane?",
  "Care e cel mai haios lucru din camera ta?",
  "Ce ți-ar plăcea să faci dacă ai fi clovn o zi?",
  "Care e cea mai amuzantă poză cu tine?",
  "Ce ai face dacă animalul tău de companie ar câștiga la loterie?",
  "Care e cel mai ciudat talent pe care îl ai?",
  "Ce ai face dacă ți-ar crește nasul ca lui Pinocchio?",
  "Care e cel mai amuzant lucru spus vreodată de un profesor?",
  "Ce ai face dacă te-ai trezi cât un gigant?",
  "Care e cea mai haioasă poveste din familia ta?",
  "Ce ai face dacă găseai o rață vorbitoare?",
  "Care e cel mai ciudat obicei al tău?",
  "Ce ai face dacă ai avea o pisică ce cântă?",
  "Care e cea mai amuzantă amintire cu cel mai bun prieten?",
  "Ce ai face dacă te-ai trezi cu solzi de pește?",
  "Care e cel mai haios lucru pe care l-ai desenat?",

  // Despre tine
  "Ce mâncare ciudată ai vrea să inventezi?",
  "Ce animal ai vrea ca profesor la școală?",
  "Ce te face să râzi cel mai tare?",
  "Ce ai face dacă vacanța ar dura un an întreg?",
  "Ce joc ai inventa dacă ai avea o superputere?",
  "Cu ce lucru mic și ciudat te lauzi cel mai tare?",
  "Ce meserie ciudată ai inventa, care nu există încă?",
  "Dacă te-ai vopsi din cap până-n picioare, ce culoare ai alege?",
  "Ce lucru haios face cel mai bun prieten al tău?",
  "La ce ești campion mondial, măcar în capul tău?",
  "Ce ai face dacă ar ploua cu broaște?",
  "Ce cântecel prostuț cânți când crezi că nu te aude nimeni?",
  "Ce talent ciudat ai vrea să ai, chiar dacă e inutil?",
  "Care ar fi cea mai ciudată țară din lume, dacă ai inventa-o tu?",
  "Ce ai face cu o vară care ține 100 de ani?",
  "Ce sunet brusc te face să sari în sus de fiecare dată?",
  "Ce joc nebun ai inventa cu prietenii tăi?",
  "Care desen animat te face să râzi cel mai tare?",
  "Ce ai construit vreodată care s-a prăbușit cu bubuit?",
  "Ce ai face dacă sâmbăta ar avea 48 de ore?",
  "Ce animal ai vrea să fii pentru o zi?",
  "Ce materie nouă și ciudată ai vrea la școală?",
  "Care e cel mai ciudat cadou pe care l-ai primit vreodată?",
  "Ce ai face dacă patul tău ar putea zbura noaptea?",
  "Ce sport ciudat ai inventa cu prietenii?",
  "Cu ce personaj dintr-un joc video ai vrea să te joci toată ziua?",
  "Ce ai vrea să mănânci la micul dejun dacă nu exista nicio regulă?",
  "Ce jucărie ciudată ai vrea să prindă viață noaptea?",
  "Ce prostie mică te face să râzi ca un nebun?",
  "Ce ai face dacă ai avea o zi liberă întreagă?",

  // Ai prefera... nebunii
  "Ai prefera să strănuți sclipici sau să râgâi baloane de săpun?",
  "Ai prefera să ai o sută de păianjeni mici sau unul uriaș?",
  "Ai prefera să miroși a flori sau a ciocolată mereu?",
  "Ai prefera să mergi de-a bușilea sau să sari într-un picior toată ziua?",
  "Ai prefera să transpiri sirop sau să plângi limonadă?",
  "Ai prefera să ai o voce pițigăiată sau o voce foarte groasă?",
  "Ai prefera să porți pantofi de clovn sau o pălărie uriașă toată viața?",
  "Ai prefera să dormi cu luminile aprinse sau fără pernă?",
  "Ai prefera să ai urechi de elefant sau nas de elefant?",
  "Ai prefera să nu mai mănânci ciocolată sau să nu mai vezi desene animate?",
  "Ai prefera să te joci în noroi sau în zăpadă toată ziua?",
  "Ai prefera să cânți tot ce spui sau să șoptești tot ce spui?",
  "Ai prefera să ai o sută de baloane cu apă la tine sau un tun cu apă?",
  "Ai prefera să fii cel mai zgomotos sau cel mai tăcut copil din clasă?",
  "Ai prefera să te dai cu skateboard-ul sau cu rolele toată ziua?",
  "Ai prefera să porți șosete diferite mereu sau pantofi diferiți mereu?",
  "Ai prefera să ai un animal de companie care sare sau unul care zboară?",
  "Ai prefera să mănânci doar lucruri verzi sau doar lucruri roșii o săptămână?",
  "Ai prefera să faci baie cu jucării de cauciuc sau cu spumă colorată?",
  "Ai prefera să ai o casă din bomboane sau o casă din prăjituri?",
  "Ai prefera să te dai cu sania vara sau cu bicicleta iarna?",
  "Ai prefera să râzi tare de tot sau să nu poți râde deloc o zi?",
  "Ai prefera să ai o pălărie care vorbește sau pantofi care cântă?",
  "Ai prefera să faci baloane de gumă uriașe sau baloane de săpun uriașe?",
  "Ai prefera să te joci afară cu prietenii sau înăuntru cu jocuri video?",
  "Ai prefera să primești o pisică sau un câine de ziua ta?",
  "Ai prefera să ai o cameră plină de jucării sau o cameră plină de cărți?",
  "Ai prefera să mănânci prăjituri sau bomboane la petrecere?",
  "Ai prefera să ai părul creț sau părul drept?",
  "Ai prefera să te joci cu apă sau cu nisip la plajă?",
];
