// Seed question bank (CAP-7). 205 kid-friendly interview questions, written
// simple and funny for ages 6-10, per
// _bmad-output/specs/spec-interview-questions/question-content-guidelines.md.
// Sentence case here; the UI applies the all-caps display transform. i18n.js
// picks _RO or _EN at load time based on the active language — keep both
// arrays the same length and order, so a given index means the same
// question in either language (translations aren't literal, matched by
// meaning/tone/section instead).
window.QUESTIONS_RO = [
  // Ai prefera...
  "Ai prefera să ai coadă de dinozaur sau aripi de fluture?",
  "Ai prefera să mănânci o broscuță de ciocolată sau un vierme de jeleu?",
  "Ai prefera să ai un cățel robot sau o pisică ce vorbește?",
  "Ai prefera să sari ca un cangur sau să te miști ca un melc?",
  "Ai prefera să ai părul verde sau pielea albastră?",
  "Ai prefera să locuiești într-un castel de dulciuri sau într-o casă din Lego?",
  "Ai prefera să zbori ca o pasăre sau să înoți ca un pește?",
  "Ai prefera să ai o sută de baloane sau un singur balon cât o casă?",
  "Ai prefera să mănânci doar înghețată sau doar pizza toată viața?",
  "Ai prefera să ai un unicorn sau un dragon ca animal de companie?",
  "Ai prefera să râzi ca o hienă sau să vorbești ca o rață toată ziua?",
  "Ai prefera să ai degete lipicioase sau picioare care se lipesc de pereți?",
  "Ai prefera să dormi într-un hamac sau într-o cadă plină de perne?",
  "Ai prefera să ai o mașină zburătoare sau o bicicletă care înoată?",
  "Ai prefera să fii cel mai rapid din lume sau cel mai puternic din lume?",
  "Ai prefera să ai ochi de pisică sau urechi de iepure?",
  "Ai prefera să mănânci supă cu bețișoare sau înghețată cu furculița?",
  "Ai prefera să ai o casă pe roți sau o casă în copac?",
  "Ai prefera să te transformi în pisică sau în câine pentru o zi?",
  "Ai prefera să ai un robot care face temele sau unul care face curat?",
  "Ai prefera să sari în piscină îmbrăcat sau să mergi la ploaie fără umbrelă?",
  "Ai prefera să ai voce de robot sau voce de desen animat?",
  "Ai prefera să mănânci un ardei iute sau o lămâie întreagă?",
  "Ai prefera să te cațeri ca o maimuță sau să sari ca o broască?",
  "Ai prefera să ai o mie de jucării mici sau o jucărie uriașă?",
  "Ai prefera să dormi toată ziua sau să te joci toată noaptea?",
  "Ai prefera să ai o pălărie magică sau o baghetă magică?",
  "Ai prefera să te plimbi cu un elefant sau cu o girafă?",
  "Ai prefera să ai gheare de leu sau coadă de maimuță?",
  "Ai prefera să plutești prin aer sau să mergi pe sub apă?",

  // Asta sau asta
  "Dragon care strănută foc sau unicorn care râgâie curcubeu?",
  "Vampir cu sughiț sau zombi care sforăie ca un tractor?",
  "Ninja care chițăie sau pirat cu papagal care vorbește?",
  "Extraterestru cu picior de pui sau robot cu coadă de purcel?",
  "Monstru sub pat sau monstru în dulap?",
  "Supererou care uită tot sau super-ticălos căruia îi e frică de întuneric?",
  "Vrăjitor cu bot de rață sau samurai cu mustață de morsă?",
  "Yeti cu papuci roz sau Bigfoot cu fundiță la coadă?",
  "Fantomă care sughite sau schelet care zdrăngăne muzică?",
  "Rechin cu dinți de iepure sau crocodil cu solzi lipicioși?",
  "Uriaș care se împiedică mereu sau pitic care sare peste tot?",
  "Broscoi vorbitor sau pisică zburătoare?",
  "Pârț sonor sau râgâială uriașă?",
  "Nas de clovn sau urechi de măgar?",
  "Castel plutitor sau peșteră secretă?",
  "Bulgăre de zăpadă sau balon cu apă?",
  "Trambulină sau tobogan de apă?",
  "Sirenă cu coadă lipicioasă sau centaur cu copite de balerină?",
  "Cap de robot sau coadă de dragon?",
  "Pantofi care scârțâie sau haine care miros a brânză?",
  "Cântat de balenă sau urlat de lup?",
  "Mustață de pisică sau coadă de veveriță?",
  "Clovn haios sau magician care dă mereu greș?",
  "Prăjitură vorbitoare sau înghețată care cântă?",
  "Coadă de sirenă sau aripi de liliac?",
  "Cizme pline cu jeleu sau pline cu spumă?",
  "Castel de bomboane sau casă de prăjituri?",
  "Tun cu apă sau tun cu baloane?",
  "Robot care pârâie sau robot care sughite?",
  "Delfin vorbitor sau papagal glumeț?",

  // Imaginație
  "Ești invizibil chiar acum, ce faci primul lucru?",
  "Profesorul tău se transformă brusc într-un dinozaur, ce faci?",
  "Găsești o comoară îngropată în curte, ce faci cu ea?",
  "Îți cresc aripi chiar acum, unde zbori primul?",
  "Deschizi frigiderul și găsești un pinguin care dansează, ce faci?",
  "Te urci într-o mașină a timpului, unde mergi primul?",
  "Te trezești mic cât o furnică, ce faci primul lucru?",
  "Primești un dragon de companie chiar acum, cum îl cheamă?",
  "Te uiți sub pat și găsești un dragon care doarme, ce faci?",
  "Primești o superputere chiar acum, care e?",
  "Ești profesor pentru o zi, ce-i pui pe copii să facă?",
  "Primești un robot personal, ce-l pui să facă întâi?",
  "Te transformi într-un animal chiar acum, în care?",
  "Mergi la baie și cada e plină cu jeleu, ce faci?",
  "Trebuie să mănânci un singur fel de mâncare toată viața, ce alegi?",
  "Găsești o baghetă magică, ce faci cu ea prima dată?",
  "Ești căpitan de pirați, cum îți numești corabia?",
  "Animalele din curte încep să vorbească, pe care-l întrebi primul?",
  "Primești o insulă doar a ta, ce construiești pe ea?",
  "Ești supererou chiar acum, ce nume îți dai?",
  "Farfuria ta începe brusc să cânte la masă, ce faci?",
  "Școala ta primește un tobogan în loc de scări, îl folosești în fiecare zi?",
  "Te transformi într-un dinozaur chiar acum, în care?",
  "Camera ta se umple brusc cu o mie de baloane, ce faci?",
  "Te trezești în interiorul jocului tău video preferat, ce faci primul?",
  "Devii invizibil chiar la școală, ce faci primul lucru?",
  "Primești un animal uriaș ca prieten, care e?",
  "Deschizi ghiozdanul și găsești un pui de dragon înăuntru, ce faci?",
  "Zbori pe un covor magic chiar acum, unde te duci?",
  "Ești vrăjitor pentru o zi, ce vrajă faci prima?",
  "Primești un castel doar al tău, câte camere are?",
  "Un dinozaur apare în curtea ta, ce îl întrebi?",
  "Urci într-o rachetă chiar acum, pe ce planetă mergi?",
  "Sună la ușă și e un urs în pijamale, ce faci?",
  "Devii cel mai puternic om din lume pentru o zi, ce faci?",
  "Te uiți în oglindă și faci fețe ciudate fără să vrei, ce faci?",
  "Te muți să trăiești sub apă, cum arată casa ta?",
  "Toți colegii tăi vin la școală costumați în dinozauri, ce faci?",
  "Primești puterea de a opri timpul, ce faci cu ea?",
  "Te transformi într-un super-câine chiar acum, ce puteri ai?",

  // Cele mai haioase
  "Care e cel mai haios sunet pe care poți să-l faci?",
  "Ce ai pune pe pizza ca să fie cel mai ciudat?",
  "Care e cea mai haioasă față pe care o poți face acum?",
  "Ce nume amuzant ai da unui pește de companie?",
  "Care e cel mai ciudat vis pe care ți-l amintești?",
  "Care e cel mai haios lucru pe care l-a făcut animalul tău?",
  "Ce joc amuzant ai inventat vreodată?",
  "Care e cea mai ciudată mâncare pe care ai gustat-o?",
  "Ce miros ciudat ai simțit vreodată?",
  "Care e cea mai amuzantă glumă pe care o știi?",
  "Ce ai face dacă ai găsi un ou uriaș în curte?",
  "Care e cel mai amuzant costum pe care l-ai purtat?",
  "Ce cuvânt amuzant îți place să spui?",
  "Care e cel mai haios nume pe care l-ai putea da unui robot?",
  "Ce dans amuzant știi să faci?",
  "Care e cel mai ciudat lucru din buzunarul tău acum?",
  "Ce ai face dacă te-ai trezi cu coadă de maimuță?",
  "Care e cel mai haios zgomot pe care îl face casa ta noaptea?",
  "Ce ți s-a întâmplat amuzant la școală?",
  "Care e cea mai ciudată aromă de înghețată la care te gândești?",
  "Ce animal face cel mai amuzant sunet?",
  "Care e cel mai haios lucru pe care l-ai crezut când erai mic?",
  "Ce ai face dacă ți-ar vorbi jucăriile?",
  "Care e cea mai ciudată poreclă pe care ai avut-o?",
  "Ce ai face dacă ar ploua cu bomboane?",
  "Care e cel mai haios lucru din camera ta?",
  "Ce ți-ar plăcea să faci dacă ai fi clovn o zi?",
  "Care e cea mai amuzantă poză cu tine?",
  "Ce ai face dacă animalul tău de companie ar câștiga la loterie?",
  "Care e cel mai ciudat talent pe care îl ai?",
  "Ce ai face dacă ți-ar crește nasul ca lui Pinocchio?",
  "Care e cel mai amuzant lucru spus vreodată de un profesor?",
  "Ce ai face dacă te-ai trezi cât un gigant?",
  "Care e cea mai haioasă poveste din familia ta?",
  "Ce ai face dacă găseai o rață vorbitoare?",
  "Care e cel mai ciudat obicei al tău?",
  "Ce ai face dacă ai avea o pisică ce cântă?",
  "Care e cea mai amuzantă amintire cu cel mai bun prieten?",
  "Ce ai face dacă te-ai trezi cu solzi de pește?",
  "Care e cel mai haios lucru pe care l-ai desenat?",

  // Despre tine
  "Ce mâncare ciudată ai vrea să inventezi?",
  "Ce animal ai vrea ca profesor la școală?",
  "Ce te face să râzi atât de tare încât pufnești pe nas?",
  "Ce ai face dacă vacanța ar dura un an întreg?",
  "Ce joc ai inventa dacă ai avea o superputere?",
  "Cu ce lucru mic și ciudat te lauzi cel mai tare, de parcă ai câștigat la loterie?",
  "Ce meserie ciudată ai inventa, care nu există încă?",
  "Dacă te-ai trezi mâine vopsit din cap până-n picioare, ce culoare ai vrea să fie?",
  "Ce lucru haios face cel mai bun prieten al tău când crede că nu-l vede nimeni?",
  "La ce ești campion mondial, măcar în capul tău?",
  "Ce ai face dacă ar ploua cu broaște?",
  "Ce cântecel prostuț cânți când crezi că nu te aude nimeni?",
  "Ce talent ciudat ai vrea să ai, chiar dacă e inutil?",
  "Care ar fi cea mai ciudată țară din lume, dacă ai inventa-o tu?",
  "Ce ai face în prima zi a unei veri care ține 100 de ani?",
  "Ce sunet brusc te face să sari în sus ca o floricică de porumb?",
  "Ce joc nebun ai inventa cu prietenii tăi?",
  "Care personaj de desene animate ți-ar plăcea să fie coleg de bancă?",
  "Ce ai construit vreodată care s-a prăbușit cu bubuit?",
  "Ce ai face dacă sâmbăta ar avea 48 de ore?",
  "Ce animal ai vrea să fii pentru o zi, ca să sperii puțin pe toată lumea?",
  "Ce materie nouă și ciudată ai vrea la școală?",
  "Care e cel mai ciudat cadou pe care ai vrea să-l primești, chiar dacă nimeni nu l-ar înțelege?",
  "Ce ai face dacă patul tău ar putea zbura noaptea?",
  "Ce sport ciudat ai inventa cu prietenii?",
  "Cu ce personaj dintr-un joc video ai vrea să faci schimb de locuri pentru o zi?",
  "Ce ai vrea să mănânci la micul dejun dacă nu exista nicio regulă?",
  "Ce jucărie ciudată ai vrea să prindă viață noaptea?",
  "Ce prostie mică te face să râzi ca un nebun?",
  "Ce ai face dacă ai avea o zi liberă întreagă și nimeni nu te-ar opri din nimic?",

  // Ai prefera... nebunii
  "Ai prefera să strănuți sclipici sau să râgâi baloane de săpun?",
  "Ai prefera să ai o sută de păianjeni mici sau unul uriaș?",
  "Ai prefera să miroși a flori sau a ciocolată mereu?",
  "Ai prefera să mergi de-a bușilea sau să sari într-un picior toată ziua?",
  "Ai prefera să transpiri sirop sau să plângi limonadă?",
  "Ai prefera să ai o voce pițigăiată sau o voce foarte groasă?",
  "Ai prefera să porți pantofi de clovn sau o pălărie uriașă toată viața?",
  "Ai prefera să dormi cu luminile aprinse sau fără pernă?",
  "Ai prefera să ai urechi de elefant sau nas de elefant?",
  "Ai prefera să nu mai mănânci ciocolată sau să nu mai vezi desene animate?",
  "Ai prefera să te joci în noroi sau în zăpadă toată ziua?",
  "Ai prefera să cânți tot ce spui sau să șoptești tot ce spui?",
  "Ai prefera să ai o sută de baloane cu apă la tine sau un tun cu apă?",
  "Ai prefera să fii cel mai zgomotos sau cel mai tăcut copil din clasă?",
  "Ai prefera să te dai cu skateboard-ul sau cu rolele toată ziua?",
  "Ai prefera să porți șosete diferite mereu sau pantofi diferiți mereu?",
  "Ai prefera să ai un animal de companie care sare sau unul care zboară?",
  "Ai prefera să mănânci doar lucruri verzi sau doar lucruri roșii o săptămână?",
  "Ai prefera să faci baie cu jucării de cauciuc sau cu spumă colorată?",
  "Ai prefera să ai o casă din bomboane sau o casă din prăjituri?",
  "Ai prefera să te dai cu sania vara sau cu bicicleta iarna?",
  "Ai prefera să râzi tare de tot sau să nu poți râde deloc o zi?",
  "Ai prefera să ai o pălărie care vorbește sau pantofi care cântă?",
  "Ai prefera să faci baloane de gumă uriașe sau baloane de săpun uriașe?",
  "Ai prefera să te joci afară cu prietenii sau înăuntru cu jocuri video?",
  "Ai prefera să primești o pisică sau un câine de ziua ta?",
  "Ai prefera să ai o cameră plină de jucării sau o cameră plină de cărți?",
  "Ai prefera să mănânci prăjituri sau bomboane la petrecere?",
  "Ai prefera să ai părul creț sau părul drept?",
  "Ai prefera să te joci cu apă sau cu nisip la plajă?",

  // Numește rapid — templated, see templates.js: {LITERA}/{CATEGORIE}/{CULOARE}
  // get a fresh random substitution every time the card is drawn.
  "Numește 5 {CATEGORIE} care încep cu litera {LITERA}!",
  "Cât de repede poți numi 3 {CATEGORIE} de culoare {CULOARE}?",
  "Numește 3 lucruri de culoare {CULOARE} din camera ta!",
  "Spune 4 {CATEGORIE} cât mai repede, fără să te oprești!",
  "Numește 2 {CATEGORIE} care încep cu litera {LITERA}, în mai puțin de 5 secunde!",
];

window.QUESTIONS_EN = [
  // Would you rather...
  "Would you rather have a dinosaur tail or butterfly wings?",
  "Would you rather eat a chocolate frog or a jelly worm?",
  "Would you rather have a robot puppy or a talking cat?",
  "Would you rather hop like a kangaroo or move like a snail?",
  "Would you rather have green hair or blue skin?",
  "Would you rather live in a candy castle or a house made of Lego?",
  "Would you rather fly like a bird or swim like a fish?",
  "Would you rather have a hundred balloons or one balloon as big as a house?",
  "Would you rather eat only ice cream or only pizza forever?",
  "Would you rather have a unicorn or a dragon as a pet?",
  "Would you rather laugh like a hyena or talk like a duck all day?",
  "Would you rather have sticky fingers or feet that stick to walls?",
  "Would you rather sleep in a hammock or a bathtub full of pillows?",
  "Would you rather have a flying car or a swimming bicycle?",
  "Would you rather be the fastest person in the world or the strongest?",
  "Would you rather have cat eyes or rabbit ears?",
  "Would you rather eat soup with chopsticks or ice cream with a fork?",
  "Would you rather have a house on wheels or a treehouse?",
  "Would you rather turn into a cat or a dog for a day?",
  "Would you rather have a robot that does your homework or one that cleans?",
  "Would you rather jump in a pool with your clothes on or walk in the rain with no umbrella?",
  "Would you rather have a robot voice or a cartoon voice?",
  "Would you rather eat a hot pepper or a whole lemon?",
  "Would you rather climb like a monkey or hop like a frog?",
  "Would you rather have a thousand tiny toys or one giant toy?",
  "Would you rather sleep all day or play all night?",
  "Would you rather have a magic hat or a magic wand?",
  "Would you rather ride an elephant or a giraffe?",
  "Would you rather have lion claws or a monkey tail?",
  "Would you rather float through the air or walk underwater?",

  // This or that
  "A dragon that sneezes fire, or a unicorn that burps rainbows?",
  "A vampire with hiccups, or a zombie that snores like a tractor?",
  "A ninja that squeaks, or a pirate with a talking parrot?",
  "An alien with chicken legs, or a robot with a pig tail?",
  "A monster under the bed, or a monster in the closet?",
  "A superhero who forgets everything, or a supervillain afraid of the dark?",
  "A wizard with a duck bill, or a samurai with a walrus mustache?",
  "A yeti in pink slippers, or Bigfoot with a bow on his tail?",
  "A ghost with hiccups, or a skeleton that rattles out music?",
  "A shark with bunny teeth, or a crocodile with sticky scales?",
  "A giant who trips constantly, or a tiny gnome who jumps everywhere?",
  "A talking toad, or a flying cat?",
  "A loud fart, or a giant burp?",
  "A clown nose, or donkey ears?",
  "A floating castle, or a secret cave?",
  "A snowball, or a water balloon?",
  "A trampoline, or a water slide?",
  "A mermaid with a sticky tail, or a centaur with ballerina hooves?",
  "A robot head, or a dragon tail?",
  "Squeaky shoes, or clothes that smell like cheese?",
  "Whale singing, or wolf howling?",
  "A cat's whiskers, or a squirrel's tail?",
  "A funny clown, or a magician who always messes up?",
  "A talking cake, or a singing ice cream?",
  "A mermaid tail, or bat wings?",
  "Boots full of jelly, or full of foam?",
  "A candy castle, or a cookie house?",
  "A water cannon, or a balloon cannon?",
  "A robot that crackles, or a robot that hiccups?",
  "A talking dolphin, or a joking parrot?",

  // Imagination
  "You're invisible right now — what's the first thing you do?",
  "Your teacher suddenly turns into a dinosaur — what do you do?",
  "You find buried treasure in your yard — what do you do with it?",
  "You suddenly grow wings — where do you fly first?",
  "You open the fridge and find a dancing penguin — what do you do?",
  "You get into a time machine — where do you go first?",
  "You wake up as small as an ant — what's the first thing you do?",
  "You get a pet dragon right now — what do you name it?",
  "You look under your bed and find a sleeping dragon — what do you do?",
  "You get a superpower right now — what is it?",
  "You're the teacher for a day — what do you make the class do?",
  "You get a personal robot — what's the first thing you have it do?",
  "You turn into an animal right now — which one?",
  "You go to the bathroom and the tub is full of jelly — what do you do?",
  "You have to eat only one food forever — what do you pick?",
  "You find a magic wand — what's the first thing you do with it?",
  "You're a pirate captain — what do you name your ship?",
  "The animals in your yard start talking — who do you ask first?",
  "You get an island all to yourself — what do you build on it?",
  "You're a superhero right now — what name do you give yourself?",
  "Your plate suddenly starts singing at dinner — what do you do?",
  "Your school gets a slide instead of stairs — do you use it every day?",
  "You turn into a dinosaur right now — which one?",
  "Your room suddenly fills with a thousand balloons — what do you do?",
  "You wake up inside your favorite video game — what do you do first?",
  "You turn invisible right at school — what's the first thing you do?",
  "You get a giant animal as a friend — which one is it?",
  "You open your backpack and find a baby dragon inside — what do you do?",
  "You're flying on a magic carpet right now — where do you go?",
  "You're a wizard for a day — what spell do you cast first?",
  "You get a castle all your own — how many rooms does it have?",
  "A dinosaur shows up in your yard — what do you ask it?",
  "You climb into a rocket right now — which planet do you go to?",
  "The doorbell rings and it's a bear in pajamas — what do you do?",
  "You become the strongest person in the world for a day — what do you do?",
  "You look in the mirror and start making weird faces without meaning to — what do you do?",
  "You move to live underwater — what does your house look like?",
  "All your classmates show up to school dressed as dinosaurs — what do you do?",
  "You get the power to stop time — what do you do with it?",
  "You turn into a super-dog right now — what powers do you have?",

  // Funniest ones
  "What's the funniest sound you can make?",
  "What would you put on a pizza to make it as weird as possible?",
  "What's the funniest face you can make right now?",
  "What funny name would you give a pet fish?",
  "What's the weirdest dream you remember?",
  "What's the funniest thing your pet has ever done?",
  "What funny game have you invented?",
  "What's the weirdest food you've ever tasted?",
  "What's the weirdest smell you've ever noticed?",
  "What's the funniest joke you know?",
  "What would you do if you found a giant egg in your yard?",
  "What's the funniest costume you've ever worn?",
  "What funny word do you love saying?",
  "What's the funniest name you could give a robot?",
  "What funny dance can you do?",
  "What's the weirdest thing in your pocket right now?",
  "What would you do if you woke up with a monkey tail?",
  "What's the funniest sound your house makes at night?",
  "What's something funny that happened to you at school?",
  "What's the weirdest ice cream flavor you can think of?",
  "Which animal makes the funniest sound?",
  "What's the funniest thing you believed when you were little?",
  "What would you do if your toys could talk?",
  "What's the weirdest nickname you've ever had?",
  "What would you do if it rained candy?",
  "What's the funniest thing in your room?",
  "What would you want to do if you were a clown for a day?",
  "What's the funniest picture of you?",
  "What would you do if your pet won the lottery?",
  "What's the weirdest talent you have?",
  "What would you do if your nose grew like Pinocchio's?",
  "What's the funniest thing a teacher ever said?",
  "What would you do if you woke up as tall as a giant?",
  "What's the funniest story in your family?",
  "What would you do if you found a talking duck?",
  "What's your weirdest habit?",
  "What would you do if you had a cat that sings?",
  "What's the funniest memory with your best friend?",
  "What would you do if you woke up with fish scales?",
  "What's the funniest thing you've ever drawn?",

  // About you
  "What weird food would you like to invent?",
  "What animal would you want as a teacher at school?",
  "What makes you laugh so hard you snort?",
  "What would you do if summer vacation lasted a whole year?",
  "What game would you invent if you had a superpower?",
  "What small, weird thing do you brag about like you won the lottery?",
  "What weird job would you invent that doesn't exist yet?",
  "If you woke up tomorrow painted head to toe, what color would you want it to be?",
  "What funny thing does your best friend do when they think nobody's watching?",
  "What are you the world champion of, at least in your own head?",
  "What would you do if it rained frogs?",
  "What silly little song do you sing when you think nobody can hear you?",
  "What weird talent would you want, even if it's totally useless?",
  "What would be the weirdest country in the world, if you invented it?",
  "What would you do on day one of a summer that lasts 100 years?",
  "What sudden sound makes you jump like popcorn popping?",
  "What crazy game would you invent with your friends?",
  "Which cartoon character would you want as your desk buddy?",
  "What's something you built that crashed down with a huge bang?",
  "What would you do if Saturday had 48 hours?",
  "What animal would you want to be for a day, just to spook everyone a little?",
  "What new, weird school subject would you want?",
  "What's the weirdest gift you'd want to receive, even if nobody would get it?",
  "What would you do if your bed could fly at night?",
  "What weird sport would you invent with your friends?",
  "Which video game character would you want to trade places with for a day?",
  "What would you want to eat for breakfast if there were no rules at all?",
  "What weird toy would you want to come to life at night?",
  "What tiny silly thing makes you laugh like crazy?",
  "What would you do with a whole free day and nobody to stop you?",

  // Would you rather... the crazy ones
  "Would you rather sneeze glitter or burp soap bubbles?",
  "Would you rather have a hundred tiny spiders or one giant one?",
  "Would you rather always smell like flowers or chocolate?",
  "Would you rather crawl everywhere or hop on one foot all day?",
  "Would you rather sweat syrup or cry lemonade?",
  "Would you rather have a squeaky voice or a super deep voice?",
  "Would you rather wear clown shoes or a giant hat for the rest of your life?",
  "Would you rather sleep with the lights on or without a pillow?",
  "Would you rather have elephant ears or an elephant nose?",
  "Would you rather never eat chocolate again or never watch cartoons again?",
  "Would you rather play in mud or snow all day?",
  "Would you rather sing everything you say or whisper everything you say?",
  "Would you rather carry a hundred water balloons or a water cannon?",
  "Would you rather be the loudest or the quietest kid in class?",
  "Would you rather skateboard or rollerskate all day?",
  "Would you rather always wear mismatched socks or mismatched shoes?",
  "Would you rather have a pet that hops or one that flies?",
  "Would you rather eat only green things or only red things for a week?",
  "Would you rather take a bath with rubber toys or colorful foam?",
  "Would you rather have a house made of candy or a house made of cookies?",
  "Would you rather sled in summer or bike in winter?",
  "Would you rather laugh super hard or not be able to laugh for a whole day?",
  "Would you rather have a talking hat or singing shoes?",
  "Would you rather blow giant bubblegum bubbles or giant soap bubbles?",
  "Would you rather play outside with friends or inside with video games?",
  "Would you rather get a cat or a dog for your birthday?",
  "Would you rather have a room full of toys or a room full of books?",
  "Would you rather eat cake or candy at a party?",
  "Would you rather have curly hair or straight hair?",
  "Would you rather play with water or sand at the beach?",

  // Name game — templated, see templates.js: {LITERA}/{CATEGORIE}/{CULOARE}
  // get a fresh random substitution every time the card is drawn.
  "Name 5 {CATEGORIE} that start with the letter {LITERA}!",
  "How fast can you name 3 {CULOARE} {CATEGORIE}?",
  "Name 3 {CULOARE} things in your room!",
  "Say 4 {CATEGORIE} as fast as you can, without stopping!",
  "Name 2 {CATEGORIE} starting with the letter {LITERA}, in under 5 seconds!",
];
