// Seed question bank (CAP-7). ~200 kid-friendly interview questions in Romanian,
// authored per _bmad-output/specs/spec-interview-questions/question-content-guidelines.md.
// Sentence case here; the UI applies the all-caps display transform.
window.QUESTIONS = [
  // Ai prefera...
  "Ai prefera să ai ca animal de companie un dragon sau un robot?",
  "Ai prefera să poți zbura sau să fii invizibil?",
  "Ai prefera să mănânci un gândac sau un vierme?",
  "Ai prefera să ai spaghete în loc de păr sau înghețată în loc de pantofi?",
  "Ai prefera să locuiești într-o casă în copac sau într-un submarin?",
  "Ai prefera să te lupți cu o rață cât un cal sau cu o sută de cai cât o rață?",
  "Ai prefera să ai ca animal de companie un elefant sau o girafă?",
  "Ai prefera să fii înalt cât o girafă sau mic cât un șoarece?",
  "Ai prefera să poți vorbi cu animalele sau să știi toate limbile din lume?",
  "Ai prefera să ai un tobogan în loc de scări sau o trambulină în loc de pat?",
  "Ai prefera să nu mai mănânci niciodată pizza sau să nu mai mănânci niciodată înghețată?",
  "Ai prefera să ai sughiț timp de o săptămână sau să te mănânce picioarele o zi întreagă?",
  "Ai prefera să călărești un dinozaur sau un inorog?",
  "Ai prefera să înoți într-o piscină cu jeleu sau într-o piscină cu budincă de ciocolată?",
  "Ai prefera să fii cel mai amuzant copil din școală sau cel mai deștept?",
  "Ai prefera să ai un dragon care scoate baloane de săpun pe gură sau unul care scoate sclipici?",
  "Ai prefera să explorezi spațiul cosmic sau adâncul oceanului?",
  "Ai prefera să cânți în loc să vorbești sau să dansezi în loc să mergi, mereu?",
  "Ai prefera să ai super forță sau super viteză?",
  "Ai prefera să locuiești pe Lună sau sub apă?",
  "Ai prefera ca cel mai bun prieten al tău să fie un robot sau un dragon?",
  "Ai prefera să mergi la școală costumat în clovn sau în dinozaur?",
  "Ai prefera să ai aripi sau coadă?",
  "Ai prefera să mănânci o lămâie întreagă sau o ceapă întreagă?",
  "Ai prefera să ai o sută de cățeluși mititei sau un singur cățel uriaș?",
  "Ai prefera să poți opri timpul sau să îl dai înapoi?",
  "Ai prefera să ai o casă făcută din dulciuri sau una făcută din piese Lego?",
  "Ai prefera să porți mereu pijamale sau mereu un costum de super-erou?",
  "Ai prefera să ai trei ochi sau trei brațe?",
  "Ai prefera să mergi cu roller coasterul în fiecare zi sau să nu mai mergi niciodată?",

  // Asta sau asta
  "Pizza sau tacos?",
  "Pisici sau câini?",
  "Vară sau iarnă?",
  "Roller coaster sau tobogane de apă?",
  "Ciocolată sau vanilie?",
  "Super-eroi sau vrăjitori?",
  "Plajă sau munte?",
  "Jocuri video sau jocuri de societate?",
  "Clătite sau vafe?",
  "Răsărit sau apus?",
  "Camping sau hotel?",
  "Popcorn sau bomboane la film?",
  "Skateboard sau bicicletă?",
  "Dinozauri sau rechini?",
  "Ninja sau pirați?",
  "Adidași sau șlapi?",
  "Desene animate sau filme?",
  "Ploaie sau zăpadă?",
  "Rachete sau submarine?",
  "Unt de arahide sau gem?",
  "Trambulină sau piscină?",
  "Roboți sau extratereștri?",
  "Benzi desenate sau cărți cu capitole?",
  "Karate sau fotbal?",
  "Marshmallows sau ursuleți de gumă?",
  "Camping în curte sau camping adevărat?",
  "Tobogane sau leagăne?",
  "Ciocolată caldă sau limonadă?",
  "Scamatorii sau jonglerii?",
  "Să construiești o fortăreață sau un castel de nisip?",

  // Imaginație și ipoteze
  "Dacă ai putea fi invizibil o zi întreagă, ce ai face primul lucru?",
  "Dacă ai putea avea orice super putere, care ar fi aceea?",
  "Dacă ai fi super-erou, care ar fi cea mai puțin impresionantă putere pe care ai putea-o avea?",
  "Dacă animalele ar putea vorbi, care ar fi cel mai obraznic?",
  "Dacă te-ai micșora cât o furnică pentru o zi, ce ai face primul lucru?",
  "Dacă ai găsi o ușă secretă în casa ta, unde ai vrea să te ducă?",
  "Dacă ai putea schimba locul cu animalul tău de companie pentru o zi, ce ai face?",
  "Dacă ai putea inventa o sărbătoare nouă, ce ai sărbători?",
  "Dacă pantofii tăi ar putea vorbi, de ce s-ar plânge?",
  "Dacă ai putea construi cea mai tare casă în copac, ce ar avea în ea?",
  "Dacă te-ai trezi uriaș, pe ce ai sta din greșeală primul lucru?",
  "Dacă ai putea scoate doar sunete de animale o zi întreagă, ce animal ai alege?",
  "Dacă ai avea o mașină a timpului, ai vizita mai întâi dinozaurii sau viitorul?",
  "Dacă ai putea face orice mâncare uriașă, ce ai alege?",
  "Dacă școala ta ar avea un etaj secret sub pământ, ce ar fi acolo?",
  "Dacă ai putea merge la școală călare pe orice animal, pe care l-ai alege?",
  "Dacă ai putea face să plouă cu orice mâncare, ce ai alege?",
  "Dacă ai putea vorbi cu tine din viitor, ce l-ai întreba?",
  "Dacă te-ai trezi mâine cu coadă, ce fel de coadă ai vrea să ai?",
  "Dacă ai putea inventa un joc nou de loc de joacă, ce ar face?",
  "Dacă ghiozdanul tău ar putea vorbi, ce ar spune despre tine?",
  "Dacă ai putea fi orice personaj de desene animate o zi, cine ai fi?",
  "Dacă ai avea un dragon ca animal de companie, unde ar dormi?",
  "Dacă ar trebui să mănânci mâncare de o singură culoare pentru totdeauna, ce culoare ai alege?",
  "Dacă ți-ai putea transforma camera în orice, în ce ar deveni?",
  "Dacă ai găsi o lampă cu duh, care ar fi prima ta dorință?",
  "Dacă ai putea vorbi cu copacii, ce crezi că ar spune?",
  "Dacă ai avea un robot care să facă o singură treabă pentru tine pentru totdeauna, ce treabă ai alege?",
  "Dacă ai putea trăi într-un joc video timp de o săptămână, pe care l-ai alege?",
  "Dacă animalul tău de companie ar putea conduce o mașină, unde te-ar duce?",
  "Dacă ai putea adăuga o materie nouă la școală, care ar fi aceea?",
  "Dacă ai putea face un animal de zece ori mai mare, pe care l-ai alege?",
  "Dacă ai avea un tobogan din camera ta până în bucătărie, l-ai folosi în fiecare zi?",
  "Dacă ar ateriza extratereștri în curtea ta, ce le-ai arăta primul lucru?",
  "Dacă ar trebui să porți un singur costum un an întreg, care ar fi acela?",

  // Cele mai nostime
  "Care e cea mai scârboasă mâncare pe care ai încercat-o vreodată?",
  "Care e cel mai ciudat lucru pe care l-ai pune pe o pizza?",
  "Care e cel mai nostim nume la care te poți gândi pentru un pește de companie?",
  "Care e cel mai amuzant sunet pe care îl poate scoate o persoană?",
  "Care e cel mai ciudat vis pe care ți-l amintești?",
  "Care e cea mai ridicolă ținută pe care ți-o poți imagina purtând-o la școală?",
  "Care e cel mai nostim lucru care te-a făcut vreodată să râzi până la lacrimi?",
  "Care e cel mai amuzant lucru care ți s-a întâmplat vreodată la masa de prânz?",
  "Care e cel mai ciudat lucru pe care l-ai văzut vreodată făcut de un animal?",
  "Care e cea mai nostimă mutră pe care o poți face chiar acum?",
  "Care e cea mai ridicolă mișcare de dans pe care o știi?",
  "Care e cel mai amuzant cuvânt pe care îl știi?",
  "Care e cea mai ciudată aromă de înghețată la care te poți gândi?",
  "Care e cea mai nostimă poreclă pe care ai avut-o vreodată?",
  "Care e cel mai ciudat lucru pe care l-ai găsit vreodată în buzunar?",
  "Care e cel mai caraghios lucru pe care l-a făcut vreodată animalul tău de companie?",
  "Care e cel mai ciudat miros pe care l-ai mirosit vreodată?",
  "Care e cel mai amuzant lucru care s-a întâmplat vreodată în pauză?",
  "Care e cel mai nostim lucru pe care l-ai crezut când erai mic?",
  "Care e cel mai ciudat talent pe care îl ai?",
  "Care e cel mai amuzant costum pe care l-ai purtat vreodată?",
  "Care e cel mai scârbos lucru în care ai călcat vreodată?",
  "Care e cel mai nostim joc pe care l-ai inventat cu prietenii tăi?",
  "Care e cel mai ciudat lucru pe care l-ai mâncat din greșeală?",
  "Care e cel mai amuzant lucru spus vreodată de un profesor?",
  "Care e cel mai ridicol lucru pe care l-ai văzut vreodată la știri?",
  "Care e cel mai ciudat zgomot pe care îl face casa ta noaptea?",
  "Care e cel mai nostim lucru pe care l-ai făcut vreodată ca să faci un prieten să râdă?",
  "Care e cel mai ciudat lucru la cel mai bun prieten al tău?",
  "Care e cel mai amuzant lucru pe care familia ta îl face împreună?",

  // Despre tine
  "Care e cea mai inutilă super putere la care te poți gândi?",
  "Care e ultimul lucru care te-a făcut să râzi în hohote?",
  "Ce îți place cel mai mult să faci când plouă afară?",
  "Care e cea mai tare farsă pe care ai făcut-o sau ai văzut-o vreodată?",
  "Care e gluma ta preferată?",
  "Care e cel mai curajos lucru pe care l-ai făcut vreodată?",
  "Care e singura mâncare pe care ai putea-o mânca în fiecare zi?",
  "Care e animalul tău preferat și de ce?",
  "Când te-ai distrat cel mai bine la o petrecere de ziua ta?",
  "Ce știi să faci foarte bine, dar puțină lume știe despre asta?",
  "Care e cel mai tare lucru pe care l-ai construit vreodată din Lego sau din cuburi?",
  "Ce îți place cel mai mult la cel mai bun prieten al tău?",
  "Care e cel mai tare cadou pe care l-ai primit vreodată?",
  "Ce ai vrea să înveți să faci?",
  "Cum îți place cel mai mult să îți petreci sâmbăta?",
  "Care e cel mai amuzant videoclip pe care l-ai văzut vreodată?",
  "Care e slujba ta de vis când vei fi mare?",
  "Care e cea mai înfricoșătoare poveste pe care ai auzit-o vreodată?",
  "Care e tradiția ta preferată de familie?",
  "Care e cea mai distractivă excursie la care ai fost vreodată?",
  "Care e melodia ta preferată de cântat tare de tot?",
  "Ce te face mereu să zâmbești?",
  "Care e cel mai tare lucru la faptul că ești copil?",
  "Ce îți place cel mai mult să construiești, să desenezi sau să creezi?",
  "Care e cel mai tare lucru pe care l-ai găsit vreodată afară?",
  "Care e gustarea ta preferată pe care majoritatea o cred ciudată?",
  "Care e cel mai tare costum pe care l-ai avut vreodată de Halloween?",
  "Care e jocul tău preferat de jucat cu prietenii?",
  "Cu ce ești foarte mândru?",
  "Care e cel mai nostim lucru de pe lista ta de dorințe acum?",
  "Ce îți place cel mai mult la vacanța de vară?",

  // Ai prefera... nebunii
  "Ai prefera să ai degete lungi cât tăițeii sau un nas lung cât trompa unui elefant?",
  "Ai prefera să strănuți sclipici sau să râgâi baloane de săpun?",
  "Ai prefera să ai o sută de păianjeni în cameră sau un singur păianjen uriaș?",
  "Ai prefera ca transpirația ta să miroasă a fursecuri sau părul tău să miroasă mereu a flori?",
  "Ai prefera să ai părul care își schimbă culoarea după dispoziție sau pielea care strălucește pe întuneric?",
  "Ai prefera să fii acoperit cu blană sau cu pene?",
  "Ai prefera să ai sprâncene unite pentru totdeauna sau mustață pentru totdeauna?",
  "Ai prefera să mergi peste tot cu spatele sau să sari peste tot într-un picior?",
  "Ai prefera să poți doar șopti sau să poți doar striga?",
  "Ai prefera să ai un animal de companie mereu lipicios sau mereu cleios?",
  "Ai prefera să mănânci o lingură de muștar sau o lingură de sos iute?",
  "Ai prefera să ai ochi pătrați sau capul în formă de triunghi?",
  "Ai prefera ca profesorul tău să îți citească gândurile sau părinții tăi?",
  "Ai prefera să nu mai poți alerga niciodată sau să nu mai poți sări niciodată?",
  "Ai prefera să transpiri sirop de arțar sau să plângi limonadă?",
  "Ai prefera să ai ca animal de companie un sconcs sau un raton?",
  "Ai prefera să porți o cască toată ziua în fiecare zi sau patine cu rotile toată ziua în fiecare zi?",
  "Ai prefera să ai o voce ca de robot sau ca de șoricel din desene animate?",
  "Ai prefera să trăiești într-o lume fără ciocolată sau fără petreceri de ziua ta?",
  "Ai prefera să ai mereu șosete ude sau mereu părul ciufulit?",
  "Ai prefera să sari ca un iepuraș sau să mergi de-a bușilea ca un crab peste tot?",
  "Ai prefera să ai un nas care claxonează sau urechi care flutură ca ale unui elefant?",
  "Ai prefera să mănânci doar supă timp de o săptămână sau doar sandvișuri timp de o săptămână?",
  "Ai prefera ca tema să ți se facă singură dar greșit sau să ai treburi în plus dar deloc teme?",
  "Ai prefera să fii cel mai înalt copil din clasă sau cel mai scund?",
  "Ai prefera un animal de companie care te complimentează toată ziua sau unul care spune glume?",
  "Ai prefera ca școala ta să aibă un tobogan de apă în loc de scări sau o piscină cu bile în loc de cantină?",
  "Ai prefera să nu mai folosești niciodată o tabletă sau să nu te mai uiți niciodată la TV?",
  "Ai prefera o sută de lei acum sau o cutie misterioasă care ar putea avea mult mai mult sau nimic?",
  "Ai prefera ca bicicleta ta să poată zbura sau skateboardul tău să poată înota?",
  "Ai prefera să miroși ca un câine ud toată ziua sau să vorbești ca o rață?",
  "Ai prefera să dai high-five tuturor celor pe care îi întâlnești sau să îi îmbrățișezi pe toți?",
  "Ai prefera să fii foarte bun la matematică sau foarte bun la desen?",
  "Ai prefera să ai o cameră fără tavan sau o cameră fără podea, dar complet sigură?",
  "Ai prefera să te bați cu bulgări de zăpadă în fiecare zi sau cu baloane cu apă în fiecare zi?",
  "Ai prefera să ai un dinozaur de companie cât o găină sau o găină de companie cât un dinozaur?",
  "Ai prefera ca profesorul să dea dulciuri pentru răspunsuri corecte sau pauză suplimentară pentru toată clasa?",
  "Ai prefera să poți respira sub apă sau să poți scoate foc pe gură?",
  "Ai prefera să cânți tot ce spui o zi întreagă sau să dansezi peste tot unde mergi o zi întreagă?",
  "Ai prefera o bătaie cu perne sau o bătaie cu pistoale cu apă cu cel mai bun prieten al tău?",
  "Ai prefera să găsești un cufăr plin cu monede de aur sau un cufăr plin cu dulciuri?",
  "Ai prefera să ai sprâncene pe care le poți mișca la comandă sau urechi pe care le poți mișca la comandă?",
  "Ai prefera să ai cel mai bun miros din lume sau cel mai bun auz din lume?",
  "Ai prefera să îți explodeze o sută de baloane deodată lângă tine sau un singur balon uriaș?",
  "Ai prefera ca tot ce atingi să se transforme în Lego sau tot ce atingi să se transforme în dulciuri?",
];
